### ISSUE TITLE
Ability to enable fine scale OSD even with a built-in display only

### ISSUE THREAD

**Issue by Volodymyr-13** [MonitorControl/MonitorControl#1000]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

On my MacBook Pro M1 2021, when I change brightness using system F1/F2 keys it changes brightness to -+ 6% or something aka one bar step: 

<img width="150" alt="nativeUI" src="https://user-images.githubusercontent.com/3391456/162585272-8cf078c2-01a7-4993-90c3-f5961970e42d.png">

So each this bar changes -+ steps too much for me, I'd like to have an **option to change -+ 1%** using F1/F2 keys 

### Describe the solution you'd like

Add option to set value of % in which each F1/F2 key press will change value of brightness. 

### Describe alternatives you've considered

In my NativeDisplayBrightness app there is such option, it changes brightness more precise, so just by adding less then -+6% for each step. 
<img width="545" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/162585379-1ff53f18-c7e4-4054-8f56-cfbf0729b3d7.png">

**Comment by the0neyouseek** [comment]
Hi @KAMIKAZEUA 
The option you're looking for is called "Use fine OSD Scale" located here in the app settings
![pref_3](https://user-images.githubusercontent.com/4009175/162589756-e592a39a-df07-4567-b879-d0743610d5bf.png)

**Comment by KAMIKAZEUA** [comment]
Hey @the0neyouseek this option didn't worked for me. Using MacBook Pro M1 2021. 

https://user-images.githubusercontent.com/3391456/162590269-2ecae7d5-0315-4a94-b598-8d29c2c6fc70.mov

**Comment by waydabber** [comment]
Hey @KAMIKAZEUA - are you using an external display or only the built-in display?

**Comment by KAMIKAZEUA** [comment]
Only built in at the moment. Just I'm not in office. While pressing Shift+Option changes smoothly.

**Comment by waydabber** [comment]
All right. The problem probably is that MonitorControl disengages from the keyboard completely when only the internal display is connected. This is intentional and is a feature actually (there were some requests towards this, I don't recall why exactly though). This might be finetuned in a way that this does not happen when the fine OSD scale is enabled.

**Comment by waydabber** [comment]
I think this was the reason:

https://github.com/MonitorControl/MonitorControl/issues/456

**Comment by KAMIKAZEUA** [comment]
I see, but this was OLD macOS. A lot was changes since that time. It's now working well, since it detects built-in display correctly. 

<img width="730" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/162591482-8485a695-5fa0-48ea-9e85-f18f66832c54.png">


Hmm, look what I found, if you just uncheck/check Brightness it will start to change smoothly: 


https://user-images.githubusercontent.com/3391456/162591584-aee10f71-f7cf-4ccf-b83f-f67b35c41867.mov

Even if I restart app, it will continue to work. But if I disable OSD scale option and then quit app - it will not work after next start, if I enable OSD scale again. But I can just uncheck/check Brightness again) 

Bug = feature)

**Comment by KAMIKAZEUA** [comment]
And yet, still it changes mostly for 2% per step.. but I'd like to have 1% per step max.. :p

**Comment by waydabber** [comment]
Hmm. Something is off there obviously. I can convert this into a feature request.

**Comment by KAMIKAZEUA** [comment]
@waydabber also, while using OSD scale for built-in display, I noted one thing: if auto-brightness enabled, it changes brightness obviously, after that if I press F1/F2 - screen will blinks in brightness level. 
So, it's not reading current value of display brightness, before apply changes to it.

**Comment by waydabber** [comment]
Hi @KAMIKAZEUA - yes, if the system changes the brightness, it does not inform MonitorControl about it. MC however polls the system brightness periodically and if it detects a change, it will alter the slider and update its knowledge about the brightness level + tries to poll faster for a while. You'll see this - if you change the brightness using the ambint light sensor (for example by covering it with your hands), you'll see your screen dim and the MC brightness slider follow it after a while.

If you however try to change the brightness using MC before MC updated its internal understanding of current brightness, the screen will flash.

**Comment by KAMIKAZEUA** [comment]
Hey @waydabber Just used this over almost all day at work. In 80% of cases it blinks brightness on F1/F2 key, which is really annoying. I'm sitting near window and looks like brightness is changing a lot, clouds are moving so it's really dynamic. 

I think this should be like maybe another bug report, since MC should read system brightness when I press F1/F2 key.
But since I'm currently using like bug=feature, this is perhaps should be considered and tested while implementing current request. If this is possible of course.

**Comment by waydabber** [comment]
But yes, you should create a separate bug report about this one. :) Thank you!

**Comment by waydabber** [comment]
Yes, you are right, I added a note to that bug about the fact that the problem is deeper than known. Honestly I use my macbook in clamshell mode mostly plus I have the ambient light sensor disabled so I did not notice the issue. Sorry about that + thank you!
