### ISSUE TITLE
automatically sync the internal display brightness with the external one.

### ISSUE THREAD

**Issue by PeterWan816** [MonitorControl/MonitorControl#1053]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

after each unlocks and device waking, it is possible that the internal display is brighter than the external display or the internal display is brighter than the external display. I have found that the setting which applies the previous settings to the screen after each device waking is useful but not working 100% of the time. For example, if I close then open the lid of my MacBook pro or if I use the control centre (touch bar) to control the brightness of the MacBook Pro, the external display will be out of sync. 

### Describe the solution you'd like

My idea is that if any changes to the internal screen are detected, the software should force the external screen to update its brightness regardless if the brightness sensor has changed. 

### Describe alternatives you've considered

using the apply last used settings to the screen after each wakes or starts. it helped with the situation of them being out of sync but not 100% working (as some of the reasons why they are out of sync is not related to wakes).

### Anything else?

it would be great if anyone is following up on this post! Thank you!

**Comment by waydabber** [comment]
There is a syncing option in MonitorControl (built-in display -> external display). It is rather rudimentary and is a differential syncing, not absolute sync so definetly there is room for improvement. :)

**Comment by andrew-stupchuk** [comment]
@waydabber sync doesnt work for me after wakes. only after restarting the app. any idea about that?

**Comment by andr2k** [comment]
It would be nice to choose the primary monitor for syncing.

In my case, I use two LG Ultrafine monitors with a laptop in clamshell mode. These monitors have their own light sensors, which work pretty well when they are independent. However, if I enable automatic brightness adjustment for both monitors, since they are differently calibrated, they react to each other (looks like a cyclic feedback loop). If I enable automatic brightness control for one of them, they end up out of sync. As a result, being able to choose a primary source of the brightness level for all the monitors would be perfect.

**Comment by waydabber** [comment]
The feature set of the app is now considered final by the team, no more feature additions are planned. I advise you to try [Lunar](https://lunar.fyi) by @alin23 as that app has various advanced syncing features. I plan implementing advanced syncing in [BetterDisplay](https://betterdisplay.pro) as well.
