### ISSUE TITLE
Add option to reset built-in screen brightness to zero after wake

### ISSUE THREAD

**Issue by anarchy89** [MonitorControl/MonitorControl#1068]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Currently, whenever I set the brightness of the internal screen to zero and it blanks out, and I set my external screens to lets say level 5. When I wake up from sleep or the Lock Screen, the internal screen becomes level 1 and the externals stay at 5.

### Describe the solution you'd like

I want the levels on each screen to stay the same when I wake the screen up.

### Describe alternatives you've considered

no alternatives. currently I have to set the screen back to zero when I turn it back on from sleep.

**Comment by waydabber** [comment]
This is a default behavior of macOS - to avoid confusion it will always set the screen to have some minimal backlighting. We could override it and restore brightness zero as a new feature.

**Comment by anarchy89** [comment]
@waydabber could you please add that as an option in the monitor control app as a new setting or something? I think a lot of people would use it. I like to keep my macbook open with the lid instead of in clam shell so it doesnt heat up too much and I always have to reduce the brightness on the internal screen when it comes out of sleep of unlocks.

thank you so much.

**Comment by anarchy89** [comment]
@waydabber never tried betterdisplay, but I am happy with setting the brightness to zero after wake. Is the screen actually off when this happens ? It looks it is. I cant see anything like I used to be able to on the older versions.

**Comment by anarchy89** [comment]
@waydabber does betterdisplay have the exact same features as monitorcontrol?

**Comment by waydabber** [comment]
@anarchy89 - nope, BetterDisplay is a different project altogether with a different vision and feature set, but I am also reimplementing much of the stuff that is in MonitorControl (since it fits the app profile) as well. Since for various reasons the app is already caring a great deal about display layouts and mirroring (this was required for the dummy and streaming functionality) it is actually a very small step to implement the option to hide the display there so it's in the roadmap.

https://github.com/waydabber/BetterDummy/issues/474

**Comment by waydabber** [comment]
(But the `option to reset built-in screen brightness to zero after wake` can be added to MonitorControl as well as that is quite a different thing, so we should keep this one here as a feature request.)
