### ISSUE TITLE
Conflict with macOS 13 Ventura Stage Manager

### ISSUE THREAD

**Issue by KevinLiu1995** [MonitorControl/MonitorControl#1088]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Stage Manager left windows disappear when open the Monitor Control.

### Steps to reproduce

1. Open Stage Manager
2. Open Monitor Control
3. Left windows disappear
4. Close Monitor Control
5. Left windows appear

### Expected behavior

Show the left windows normally.

### Environment Information (please complete the following information)

```markdown
- macOS version:13.0
- Mac model:MacBook Pro (15-inch, 2019)
- MonitorControl version:v4.1.0
- Monitor(s):AOC U27N3G6R4B
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
See the reason here: https://github.com/waydabber/BetterDisplay/issues/717

**Comment by tomkap011** [comment]
@waydabber, this seems to be fixed in the current build 

## Attempting to replicate
![CleanShot 2022-09-03 at 14 54 44](https://user-images.githubusercontent.com/84490604/188287445-291e3fa3-70b2-4970-8c6d-6bf849c2f994.gif)
## version 
<img width="263" alt="CleanShot 2022-09-03 at 14 56 58@2x" src="https://user-images.githubusercontent.com/84490604/188287450-b2b58bff-7a7d-4853-8e88-e57318a42f59.png">


Maybe consider closing

**Comment by waydabber** [comment]
Wow, great! Thanks for the feedback, I did not test it since but just had the thought to retest it the other day.

**Comment by waydabber** [comment]
Indeed it works, even with overlay dimming, so this is great news! I'll close this one.
