### ISSUE TITLE
Handle monitors with no sound

### ISSUE THREAD

**Issue by the0neyouseek** [MonitorControl/MonitorControl#11]
Better handle monitor with no sound if possible

- [ ] Detect monitor with no sound
- [ ] Do not display the sound slider
- [ ] Sound control should "pass-through"

**Comment by falcn** [comment]
Unless detection would work flawlessly for a wide variety of monitors, a simple checkbox to disable volume slider would be better. My monitor (Dell P2715Q) has a sound pass through, but volume can't be controlled by ddcctl, it's always 100%.

**Comment by JoniVR** [comment]
Status update on this issue:

> - [ ] Detect monitor with no sound

I think this can be considered done? 
We currently detect the active output and disable key interception for volume when the active output can "set its own volume". I guess we could disable the slider too.

> - [ ] Do not display the sound slider

Partially, using a checkbox in #213, should also disable the slider if the device can set it's own volume automatically?

> - [x] Sound control should "pass-through"

Happens when default output device can set it's own volume.

**Comment by waydabber** [comment]
We have the checkbox now.

We could add detection of Volume control capability (using the f3 capability check ddc command), but this is rather finicky and a good amount of displays do not support this properly. This means that a manual override would still be needed on a per monitor basis, so I think it's easier to add disable volume control as an option in the advanced section of the displays page of preferences.

Also it would be beneficial for users to give the ability to explicitly tell the app which MacOS audio output to control (by name) as an advanced option - in a multi monitor setup most probably only one display will be used as speaker and the current method of determining which display to control (based on mouse cursor location) is not relevant in this regard.

Also, somewhat related to this is that an option might be given to assume control if a specific output is selected even if the given output is reported as volume controllable by the OS - since many audio filters report as such (ones like Boom), but digitally controlling the amplifier through the display is better than letting Boom do software control.

**Comment by yangkennyk** [comment]
would be great if it was possible to use with Boom 3D.

**Comment by waydabber** [comment]
We'll have the following in 3.1.0:

- Selectable independently whether all display's volume should be controlled.
- Individual display control can happen based on mouse location or audio device name matching (if the audio device name is "LG Ultra HD" for example, then only the display which has this name will be controlled via the volume keys.
- Ability to make volume control unavailable for a display in the advanced section.
- Using 'Override audio device name' you'll have the option to assign a display to a specific audio device name (like Boom 3D) - so volume keys will control the display when this audio device is selected even if it reportedly has its own volume controls.

<img width="803" alt="Screen Shot 2021-09-12 at 19 09 48" src="https://user-images.githubusercontent.com/37590873/132996720-362ad923-a57a-424c-bf82-3500a0d13edb.png">

Additionally you'll be able to limit the volume min/max and change the scale skew (in favor of finer control at lower volumes). Also, slider snapping is disabled by default so volume control at the extremities would be easier.

Hopefully with these in place there won't be more room for complaint on the audio department. :)
