### ISSUE TITLE
Support for custom key shortcuts

### ISSUE THREAD

**Issue by KAMIKAZEUA** [MonitorControl/MonitorControl#118]
I have a macmini and a simple keyboard. How to control brightness via keys?
Just want to assign custom Key's for some action. For example, F1-F2 for brightness. 

Perhaps, basically something like: 

<img width="265" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/63844123-487aed00-c990-11e9-9807-b52d42414c5a.png">

edit: in my app it was dumb simple) 
https://github.com/KAMIKAZEUA/NativeDisplayBrightness

<img width="307" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/3391456/63844627-3188ca80-c991-11e9-8bf8-764956764e3b.png">

**Comment by JoniVR** [comment]
Always welcome to make a PR if you want to! :)

**Comment by KAMIKAZEUA** [comment]
I don't know swift at all and I don't like it :), but honestly, the main problem - I don’t have time to support my program or any other. Just found yours and it's looks almost perfect, excepts keys and also smooth brightness change :) like just by +-1%

**Comment by JoniVR** [comment]
Smooth brightness/volume should work like it does natively on a mac using <kbd>shift</kbd> + <kbd>alt</kbd> modifiers :)

**Comment by KAMIKAZEUA** [comment]
Okay, I see. But just for constant and precise control I've set smooth option enabled by default. Never used Apple keyboard's..

**Comment by KAMIKAZEUA** [comment]
@JoniVR Any news :) ?

**Comment by Bogey** [comment]
I can tell that KAMIKAZEUA's NativeDisplayBrightness works on my rig. 
Though I have to disable Display Keyboard shortcuts in System Preferences and set them in NativeDisplayBrightness.

Setting brightness with MonitorControl _only_ works with the slider.
With the keys I can only control the sound, though I would like to remap these keys because the keys overtake the default MacOS sound output. My speakers are connected to the computer and not the monitor. The monitor has headphones that I use at night.

Perhaps the keys are working, but my keyboard cannot pass them on ... if MonitorControl is listening for F13/F14 -- because I don't have those keys.

Keyboard I'm using is Logitech K780 and monitor is LG 25UM58-G

**Comment by Bogey** [comment]
This is the one I'm currently using:
https://github.com/fnesveda/ExternalDisplayBrightness

**Comment by JoniVR** [comment]
Just an fyi, I am working on this but it requires quite a big rewrite and I don't have that much free time right now.. so it might take me some time.

**Comment by KAMIKAZEUA** [comment]
@JoniVR Hey, is this implemented?

**Comment by JoniVR** [comment]
Not yet, I decided that I would be too many changes at once, I do plan on implementing it in the future though. Sorry if you were waiting for it.

**Comment by CharlesCCC** [comment]
Looking forward to this feature,  because I noticed I can only adjust brightness with the Apple Magic Keyboard, non other keyboard(PC keyboard) can be used to adjust the brightness. which is the only thing that I miss about this App, everything else was perfect. (it all worked quite well with my LG 34 UltraWide along with two 4k AOC monitors). Love it, thank you for the great work.

**Comment by sovon** [comment]
Hi, I'm a long time user of this utility. My 3rd wired Apple Magic Keyboard died and I have bought this **Logi K380** keyboard recently.

 If I map **F6** and **F7** from System Preferences>Keyboards>Shortcuts>Display I can control the brightness of my laptop's built in display(with Fn+F6) but it doesn't affect the external monitor. I could easily use Logitech Options but I don't want to use a separate tool just for this one single feature.

Can you please add a feature so that MonitorControl listens to the Fn commands or maybe add a custom key binding feature, whichever is simpler?

<img width="669" alt="Screenshot 2020-08-02 at 8 29 36 PM" src="https://user-images.githubusercontent.com/18725800/89125890-2de5b800-d4ff-11ea-98c4-598c665b7cff.png">

<img width="1036" alt="Screenshot 2020-08-02 at 8 23 53 PM" src="https://user-images.githubusercontent.com/18725800/89125743-3b4e7280-d4fe-11ea-8a5d-447c5575157a.png">

**Comment by CharlesCCC** [comment]
Note: Today I just noticed my keyboard (microsoft sculpt ergonomic keyboard) works perfect for the default brightness control; 
 the **ScrLk** is F14, **Pause** is F15, which corresponding to brightness change for Mac. (It works perfect in my MBP and my Hackintosh) and it works regardless if the keyboard is in the Function model or not.

**Comment by adrien3d** [comment]
@JoniVR any updates on this feature ? Thank you very much for your work so far ;)

**Comment by JoniVR** [comment]
I unfortunately don't have a lot of time lately, I'm trying to push through as many stability improvements as I can when I get the time but unfortunately the way MonitorControl is currently written, supporting custom shortcuts isn't really that easy to implement, it's a big feature that needs proper time and care. If anyone else feels up for the task I'd be more than happy to accept PRs for it though.

**Comment by waydabber** [comment]
There are some custom shortcut requests and these are legit I think, MC should be adding this as an option. As I checked out MediaTapKeys' code it could be added easily. Also there are other solutions as well out there which could be integrated if needed.

**Comment by waydabber** [comment]
Something like this will suffice I hope:

<img width="803" alt="Screen Shot 2021-09-28 at 20 32 15" src="https://user-images.githubusercontent.com/37590873/135145474-a46f54f3-c524-4883-a27a-d152ba2cee17.png">

Thing is getting a bit more complicated than I thought as I'll have to simulate keyboard repeat which is not happening with shortcuts.

**Comment by aik099** [comment]
> Something like this will suffice I hope:
> 
> <img alt="Screen Shot 2021-09-28 at 20 52 36" width="803" src="https://user-images.githubusercontent.com/37590873/135148223-c5ed944a-25ff-46fb-ade7-31ade57c02c9.png">
> 
> Thing is getting a bit more complicated than I thought as I'll have to simulate keyboard repeat which is not happening with shortcuts.

Sure, @waydabber .

**Comment by waydabber** [comment]
This is now working nicely as far as I was able to test. Also added keyboard repeat support.
