### ISSUE TITLE
Can't turn volume down to off on Samsung C49J89x

### ISSUE THREAD

**Issue by krajniak** [MonitorControl/MonitorControl#1190]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

When I turn my volume down to 0, or mute it my Samsung C49J89x still provides low volume sound

### Expected behavior

After setting volume to zero, monitor volume should also by 0

### Environment Information (please complete the following information)

```markdown
- macOS version: Monterey 12.5.1 (21G83)
- Mac model: MacBook Pro (16-inch, 2019)
- MonitorControl version: 4.1.0 build 7034
- Monitor(s): Samsung C49J89x
- Monitor Cable(s)/Connection(s): thunderbolt
- Apple Silicon/M1 (yes or no): no
```

**Comment by the0neyouseek** [comment]
Hi @krajniak

MonitorControl does not issue a "real" mute command due to various issue discovered on several monitors while working on this app. Volume is simply set to zero. you can however try to enable "true" mute in the app "Display" settings after enabling "Advanced setting" and see if works for you

**Comment by krajniak** [comment]
Oh! Didn't notice this settings, It's working!
Thanks a lot!

As a side note, maybe you could consider making this "advance settings" more visible
