### ISSUE TITLE
Sound control not working M2 Pro Apple Silicon and DELL U3421WE 

### ISSUE THREAD

**Issue by paunin** [MonitorControl/MonitorControl#1309]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Even sound pannel appears for change of the sound but Monitor does not react.
Worked ok with same monitor and intel chip

![image](https://user-images.githubusercontent.com/500074/217178238-15ebb559-ac81-4af9-b231-47c975f02539.png)
![image](https://user-images.githubusercontent.com/500074/217178259-3db6cd01-eb6d-4119-b407-2c3b68f23d88.png)
![image](https://user-images.githubusercontent.com/500074/217178538-6c8363c3-a547-4eaf-a7b2-3e737e85f6ba.png)
![image](https://user-images.githubusercontent.com/500074/217179344-0dfe393a-ed50-4e05-aa75-d720ee64ade5.png)
![image](https://user-images.githubusercontent.com/500074/217179334-36402ebf-b2e6-4764-81da-ed414025e2c5.png)

### Steps to reproduce

1. Install
2. Try to change volume

### Expected behavior

Sound is changing for monitor

### Anything else?

Brightness works fine BTW

### Environment Information (please complete the following information)

```markdown
- macOS version: 13.2
- Mac model: Macbook M2 Pro
- MonitorControl version: 4.1.0
- Monitor(s): DELL U3421WE 
- Apple Silicon/M1 (yes or no): Apple M2 Max
```

**Comment by miszterx** [comment]
Same issue with me.

**Comment by waydabber** [comment]
DDC generally does not work on M2 Pro systems with MonitorControl right now. This will be fixed in the future. Check out this for an alternative for now: https://github.com/MonitorControl/MonitorControl/discussions/1299

**Comment by paunin** [comment]
@waydabber not really nice, dude. You are redirecting to a paid software (which I believe is good) for a simple, and I think, core feature... 🫠

**Comment by waydabber** [comment]
You are right of course, sorry about that, removed it from the thread above. It's just that the "not supported on M2 Pro" issue pops up in various iterations and to me it feels bad just closing them (because of duplication) and not pointing ppl to somewhere - and currently I have no knowledge of any open source alternative. Plus all the DDC feature in BetterDisplay is totally free and not limited in any way. I plan to add these features to MC as well eventually, but of course anybody else in the community is open to work on it for the open source cause (it might actually be healthy for somebody else to give this issue some time and thought and take credit for it) - I or the other maintainers will not stand in the way of any PR regarding this! :)

**Comment by davidkim10** [comment]
Just got my new macbook and noticed I also lost control to my external sound through this app. Love this app and hope a PR is created soon to address the issues with the M2 chip.

For the short term if anyone needs an app to control external audio devices I am using SoundSource and it is working well with the new m2 macbooks.

https://rogueamoeba.com/soundsource/

**Comment by dellhem** [comment]
Is there an open issue about this that I can follow? I prefer the simplicity of MC over BD :)

**Comment by waydabber** [comment]
Sure: https://github.com/MonitorControl/MonitorControl/issues/1301
