### ISSUE TITLE
MonitorControl will not work when the Mac wakes from sleep

### ISSUE THREAD

**Issue by chen1912** [MonitorControl/MonitorControl#1349]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When the Mac wakes from sleep, MonitorControl will not work and the brightness of the built-in display will be dimmed (the display will not turn off). The automatic brightness adjustment fails, and the software needs to be restarted to work properly.

### Steps to reproduce

close the laptop lid，wait Mac sleep, than weak it up.

### Expected behavior

Not work.

### Anything else?

None

### Environment Information (please complete the following information)

```markdown
- macOS version:Ventura 13.2.1
- Mac model:Macbook Pro 2018
- MonitorControl version:4.1.0 7034
- Monitor(s):LG-27UL850
- Apple Silicon/M1 (yes or no): no
```

**Comment by waydabber** [comment]
Can you try [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme) and see if you have the same issue?

**Comment by djrobx** [comment]
I have a sort of similar problem.  In my case I'm using just software dimming.   When I sleep my mac, the display comes back on at full brightness.   The UI shows the correct dimming level.   I have to bump the brightness up or down to apply it again.   It seems like MonitorControl doesn't reapply the dimming level after the machine wakes up from sleep.  I'm using two LG C2 TVs that don't support DDC on Ventura 13.3

**Comment by Volodymyr-13** [comment]
Same here, not working at all for USB-C connected external monitor after sleep. But it's not 100%, I'd say in 10% chance I got this bug.
Just restart the app and everything will work again.

I didn't try a betterdisplay because it's super overwhelmed with some features.. I never need and to find something simple is so hard, a lots of menus items, structure is so hard.. to just quickly catch something I need. I even can't imagine that changing brightness could be such a super advanced thing.. 
No, I'm not try to joke here, this is how it goes. I just interested in a simple app only.. which does a simple thing - change brightness. 🤷‍♂️

**Comment by Volodymyr-13** [comment]
Also, I have another issue, but I think it's definitely related as I think. 
It lose DDC after sleep. Just randomly, using USB-C. 
And just restart app, everything is restored. 
<img width="300" alt="Screenshot 1" src="https://github.com/MonitorControl/MonitorControl/assets/3391456/d9dbaca5-4040-40f0-a885-6ec67a65e8db"><img width="300" alt="Screenshot" src="https://github.com/MonitorControl/MonitorControl/assets/3391456/089ee81a-6a4a-4510-84ff-35d785af73c1">

<img width="300" alt="Screenshot 4" src="https://github.com/MonitorControl/MonitorControl/assets/3391456/ed1b117e-0cf0-4a20-a5e6-454495977ac1">

**Comment by mustdobetter** [comment]
+1 for this issue. I am using my Macbook Pro M1 in clamshell mode, with an LG C2 via USB-C -> HDMI (Cable Matters). I am using BetterDisplay only for the custom EDID to allow me to achieve 120hz refresh rate on the LG. I have all brightness controls disable in BetterDisplay including software and DDC, as I much prefer to use MonitorControl's gamma table modification for brightness adjustment.

Everything works well except that when waking from sleep, brightness controls do nothing. Restarting the app brings this back.

```
- macOS version: 14.1.1 Sonoma
- Mac model: MacBook Pro 14 2012 M1 Max
- MonitorControl version: 4.2.0 Build 7048
- Monitor(s): LG C2 (4k 120hz)
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi @mustdobetter - BetterDisplay has the same gamma table modofication for brightness adjustment. You should disable Hardware Brightness Control only in the app so it uses gamma only.

**Comment by mustdobetter** [comment]
Hi @waydabber. Thanks - I've tried this, however when disabling Hardware Control, leaving Software-based enabled, when changing brightness the the mouse pointer stays at full brightness, and if I use the Apple Digital Color Meter app on any of the adjusted area, it shows a change to the colour values. This would suggest that it's not gamma table modification, but rather an overlay that's being used. Is that not correct?

**Comment by waydabber** [comment]
Hi, right. You must have color controls disabled (probably due to compatibility reasons, maybe you ran the app alongside MonitorControl and the two clashed) so and the app is falling back to overly control.

You should check this as a general setting:

<img width="902" alt="Screenshot 2024-01-17 at 15 06 22" src="https://github.com/MonitorControl/MonitorControl/assets/37590873/36f68c2f-5142-45b0-a257-67d7ee482ca1">

There is a per display setting as well:

<img width="902" alt="Screenshot 2024-01-17 at 15 07 06" src="https://github.com/MonitorControl/MonitorControl/assets/37590873/58fd5548-c384-4d28-98e3-0926f266864c">

**Comment by mustdobetter** [comment]
Ah, @waydabber, that was it - thank you! Now just to solve the issue of BD crashing occasionally after wake - but I'll move that to the BD issue list. Thanks for your help!

**Comment by waydabber** [comment]
Hopefully this issue is resolved with the latest version. If not, will reopen. :)
