### ISSUE TITLE
Menu Bar Panel overflowing on Spanish

### ISSUE THREAD

**Issue by stonkol** [MonitorControl/MonitorControl#1499]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

The problem is not appearing in the English version, but in the Spanish one.
![overflowing_es](https://github.com/MonitorControl/MonitorControl/assets/12591176/08aada4a-4294-4475-b256-d8b5b71ebc52)

### Steps to reproduce

1. Click Menu Bar Icon

### Expected behavior

Shouldn't be overflowing.

### Environment Information (please complete the following information)

```markdown
- macOS version: 14.2.1 Sonoma
- Mac model: MacBook Pro
- MonitorControl version: 4.2.0
- Apple Silicon/M1: yes
```

**Comment by waydabber** [comment]
Anyway, I just change it to "Actualizaciones…". ChatGPT says it's fine:

"In that context, “Actualizaciones…” wouldn’t look weird at all in an app menu, especially if the other UI elements provide further explanation. Since it sits between “Preferencias…” and “Cerrar,” it seems perfectly fine, especially given that the context will make it clear that it’s related to updates.

It should blend well with the other menu items and maintain a consistent, clean look."

:)

**Comment by stonkol** [comment]
Hey, sorry for late reply. Yes Is it solved and the translation also works.
