### ISSUE TITLE
The app does break HDR color on v4.2.0

### ISSUE THREAD

**Issue by andkirby** [MonitorControl/MonitorControl#1529]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

Once MacBook Pro connected to the a monitor (or woken up) HDR is broken.
Quitting the MonitorControl app resolves the issue.

### Steps to reproduce

1. Connect a MacBook to a monitor and enabled HDR.
2. Open an HDR video (https://www.youtube.com/watch?v=OjHbS-_nncw&t=420s)
3. Put the laptop to sleep or unplug it.
4. Wake up or plug-in the laptop back.
5. Check opened HDR video.

### Expected behavior

HDR works normally after restored connection to a monitor.

### Anything else?

It's expected brightness adjustments breaks HDR. Probably it worth to lock it somehow.

### Environment Information (please complete the following information)

```markdown
- macOS version: 14.3
- Mac model: MacBook Pro '21 M1
- MonitorControl version: 4.2.0
- Monitor(s): MSI MAG323UPF
- Apple Silicon/M1 (yes or no): yes
```

**Comment by battistellafilm** [comment]
Since installing this app and then deleting it I have found it severly reduced the brightness of the monitor compared to the monitors bright prior to installing this application. 



- macOS version: 13.6.5
- Mac model: Macmini M1
- MonitorControl version: 4.2.0
- Monitor(s): Apple Cinema display 9226
- Apple Silicon/M1 (yes or no): yes

**Comment by waydabber** [comment]
@andkirby - software dimming (color table manipulation) indeed clips HDR brightness. However the app should be restoring HDR range when software brigthness is at 100% or when DDC brightness control is used (note: most HDR displays don't like DDC control in HDR mode).

@battistellafilm - the issue is related to the max DDC brightness level for the Cinema displays, DDC max levels need to be set to 255. There are several discussions and tutorials about it under the project Discussions tab.

**Comment by andkirby** [comment]
@waydabber , thank you for your reply and explanation.
Yes, it looks like it's a dead-end. I gave on changing brightness via this way.
