### ISSUE TITLE
❓ Why MonitorControl stopped accepting donations?

### ISSUE THREAD

**Issue by wmsenna** [MonitorControl/MonitorControl#1568]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

The "donate" button in the preferences tab takes you to the website https://opencollective.com/monitorcontrol/donate. Then, an error pop-up appears: "This account cannot receive financial contributions at this time."

### Steps to reproduce

1. Go to the "donate" button
2. Enter in the website https://opencollective.com/monitorcontrol/donate
3. See the error "This account cannot receive financial contributions at this time."

### Expected behavior

Any website that allows donations to the creators of this product.

### Environment Information (please complete the following information)

```markdown
- macOS version: 14.3 Sonoma
- Mac model: MacBook Pro (14-inch, 2023)
- MonitorControl version: v4.2.0
- Monitor(s): Irrelevant
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Hi there,

indeed, we decided to stop accepting new contributions for now as the team felt that MonitorControl has reached its maturity and any more features would only deduct from it's simplicity for which the app is liked by many.

If you'd like to contribute to the development of such tools or want more features, I recommend getting a Pro license for the following apps (listed in alphabetical order):

- **[BetterDisplay](https://github.com/waydabber/BetterDisplay)** by me (@waydabber) - comparison with MonitorControl [here](https://github.com/waydabber/BetterDisplay/wiki/List-of-free-and-Pro-features)
- **[Lunar](https://lunar.fyi)** by @alin23 - comparison with MonitorControl [here](https://lunar.fyi/#comparison)

Both Lunar and BetterDisplay have great free features and a lot of advanced features for Pro users. BetterDisplay has all of MonitorControl's features (and then some) for free and a somewhat similar-feeling UI (for obvious reasons, having the same designer/programmer) that probably makes transitioning easier for MonitorControl users, while Lunar has a bold, intuitive UI, most advanced syncing capabilities and external hardware support.

It is important to note that @alin23 spearheaded figuring out DDC support for Apple Silicon Macs and thus contributed in important ways to the success of MonitorControl and I (@waydabber) did most of the coding work on MonitorControl since version 3.0 (with the help of my fellow project maintainers), building upon the great work of those who started the project. Because of this, those who are grateful for MonitorControl or want a more features than what MonitorControl has to offer, do well by getting one or both of these apps (note: the two apps can be configured to work together). 😄

**Comment by the0neyouseek** [comment]
I'll add that you can still thanks the main maintainers of this project individually if you wish to
* @the0neyouseek : [Github Sponsors →](https://github.com/sponsors/the0neyouseek)
* @waydabber : [Purchase a BetterDisplay Pro license →](https://betterdisplay.pro/buy/)
* @JoniVR

**Comment by antoniopassarelli** [comment]
can't this be closed?

**Comment by waydabber** [comment]
Let me reopen this. Here is link to a follow-up discussion about some concern about the decision regarding donations:

https://www.reddit.com/r/mac/comments/1e30j3h/possible_limitation_of_monitorcontrol_development/?rdt=59029
