### ISSUE TITLE
Volume control not available when the display is in HDR mode in Sequoia

### ISSUE THREAD

**Issue by yunogi** [MonitorControl/MonitorControl#1617]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

- I have two monitors, and I always use the speaker of my main monitor, and it supports DDC control by using MonitorControl.

- However after I upgraded to MacOS 15, and update the MonitorControl to 4.3 beta to avoid HDR crash, I can no longer change the volume as "Use Hardware DDC control" option is unavailable.

- But if I disconnect my second monitor, "Use Hardware DDC control" option is back to normal, and I can change the volume this time.

### Steps to reproduce

1. Two monitors connected
2. Use the HDR monitor speaker to play sound
3. Check "Use Hardware DDC control" option status, and try to change volume.
4. Disconnect the second monitor and check "Use Hardware DDC control" option status, and try to change volume once again.

### Expected behavior

1. MonitorControl should show "Use Hardware DDC control" option available when using multiple monitors
2. MonitorControl should change the volume of the right monitor

### Anything else?

Abnormal:
![Screenshot 2024-09-24 at 10 49 02](https://github.com/user-attachments/assets/d8112e3b-9269-4742-96fb-f0627331c4fc)

Normal:
<img width="727" alt="Screenshot 2024-09-24 at 10 48 36" src="https://github.com/user-attachments/assets/2ce284f3-1a6d-4d33-af94-3b94ff3193fa">

### Environment Information (please complete the following information)

```markdown
- macOS version:MacOS 15 Sequoia
- Mac model:Mac Studio 2022
- MonitorControl version:4.3 beta Build 7083
- Monitor(s):Dell U2417H and LG 32UN880 
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
The current version of MonitorControl will fall back to Apple control when available. In Sequoia, third party HDR display a software brightness control (that remaps peak SDR brightness up to 500 nits) - the app interprets this as native control and assumes the display has full native control, that's why volume control is disabled.

This issue might be fixed in some future version, however a more thorough reengineering of MonitorControl would be needed to gracefully handle this and provide both DDC and native brightness control for a display at the same time. I don't think this will be fixed in the outdated v4.x codebase (I see no point but of course other contributors are welcome to work on this).

I recommend using [BetterDisplay](https://github.com/waydabber/BetterDisplay#readme) as it has this elegantly resolved. All features of MonitorControl is available in BetterDisplay for free.

**Comment by waydabber** [comment]
Ok, fixed this. The app will detect a display in HDR mode and refrain from identifying it as Apple display thus continue to use DDC control. The SDR peak brightness can be changed using Control Center.
