### ISSUE TITLE
App version v4.2.0 and earlier update no longer works

### ISSUE THREAD

**Issue by jussikuosa** [MonitorControl/MonitorControl#1625]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

https://monitorcontrol.app/ gives 

```
Error 1000 Ray ID: 8c99f6d8d8deca81 • 2024-09-27 08:01:10 UTC
DNS points to prohibited IP

What happened?

You've requested a page on a website (monitorcontrol.app) that is on the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. Unfortunately, it is resolving to an IP address that is creating a conflict within Cloudflare's system.
What can I do?

If you are the owner of this website:
you should [login to Cloudflare](https://www.cloudflare.com/login?utm_source=error_100x) and change the DNS A records for monitorcontrol.app to resolve to a different IP address.
```

### Steps to reproduce

Try to browse to https://monitorcontrol.app/ 

### Expected behavior

Able to see the site and download the latest release

### Anything else?

This started from me noticing that the control app doesn't update both monitors anymore. I tried to upgrade the app but that fails (likely due to the DNS issue described).

See:  External Keyboard Brightness Control Not Working on All Monitors #1531 for my root problem.

### Environment Information (please complete the following information)

```markdown
-
```

**Comment by waydabber** [comment]
The current version of MonitorControl app is no longer upgradable. Although the DNS issue will be fixed, future updates will not work from the v4.2.0 version.

**Comment by Chathkay** [comment]
yeah no longer works, instantly crash when trying to adjust brightness on m1

**Comment by Hassan0x00A** [comment]
> The current version of MonitorControl app is no longer upgradable. Although the DNS issue will be fixed, future updates will not work from the v4.2.0 version (due to an issue with the required digital signatures).

Is the project is still being actively maintained? Are there plans for future releases to address these issues or will the current version be the last? Any clarification would be helpful.

**Comment by waydabber** [comment]
Take a look at the recent discussion here @Hassan0x00A - https://github.com/MonitorControl/MonitorControl/issues/1570

I plan to do something with the repo, possibly release a more official beta of 4.3.x. Updates from 4.2.0 will not work due to a signing issue. However currently only about 6-7k ppl downloaded the 4.3.1 version so I am not even sure how much demand there is for MonitorControl anymore (I think BetterDisplay is clearly a better alternative for most both in terms of functionality and support), so I have some doubts on whether I should work on a MonitorControl 5.0 or not.

**Comment by Hassan0x00A** [comment]
I've tried BetterDisplay but I find it a bit overwhelming as there are a lot of options that I don't need. I was looking for something simple to control the brightness of my external monitors, and I think most people need the same.

**Comment by waydabber** [comment]
Right. I am not sure about most people based on download stats, but I get that there is a certain number of users who prefer MonitorControl, that's why I released an unofficial version that mostly works on Sequoia - feel free to use it! :) I certainly welcome other developers joining in to help ironing out any issues the version still has.

**Comment by waydabber** [comment]
To some extent, yes. Accessibility permissions will likely break. But I think brew should be able to install the new version (when and if one is provided).

**Comment by JamesTJRead** [comment]
BetterDisplay is overkill - I just to control an external monitor with my keyboard.. this utility nails that task, very keen on a new version that address the Sequoia issue. 

Wouldn't be surprised about low download stats for a beta version, personally I only found this repo once the app stopped working, it was something I installed years ago and forgot about while it worked in the background.

**Comment by waydabber** [comment]
Ok, fixed the DNS issue with the update. This will not make future updates work, but at least for now the user will not get an error message but will be reassured that the 4.2.0 is the latest version.
