### ISSUE TITLE
Control volume of selected output device regardless of focussed display

### ISSUE THREAD

**Issue by tbrodbeck** [MonitorControl/MonitorControl#176]
Hey, as an feature request, it would be awesome to be able to only have one output device that can be controlled when focussing any screen. 
Usually you do not use your monitor and your local speaker both at the same time, right?

**Comment by JoniVR** [comment]
You mean that it tries to control the volume of the internal display when it's in focus even though the output is set to the external one? I agree in that case!

**Comment by mischkl** [comment]
@JoniVR I don't think that's what's meant. Normally there is just one sound output at a given time, and that's by design - if I connect my Mac to an external device that supports audio, and switch my output device in the Mac audio menulet to that external device, then it means I want all audio routed through that device.

As an example, I have external speakers hooked up to my monitor, so I can just plug in my Mac with a single cable and audio is routed to the external speakers. If I play a YouTube video on my internal screen, I still want the audio to be routed to the external speakers. And I want to be able to set the volume on the external speakers via the volume keys, despite the fact that the internal screen is currently focused.

**Comment by JoniVR** [comment]
I think I understand what you mean and that's what I meant too. 

Currently, when you select your internal display it ignores the selected output because the internal display is "focussed". I think this is pretty easily fixed though, I just need to find some time to look into it (and a whole range of other stuff in this project lol)

**Comment by mischkl** [comment]
Any chance this will make it into the next release?

**Comment by JoniVR** [comment]
There’s a similar issue that’s probably related to this. I haven’t had the time to look into it and I can’t promise you a timeline either. Anyone is free to implement it though. If not I’ll try to get around it eventually.
