### ISSUE TITLE
Lag on Macbook pro when using hyperdrive thunderbolt dock

### ISSUE THREAD

**Issue by Alexandoooor** [MonitorControl/MonitorControl#199]
So I got a hyperdrive thunderbolt 3 dock for my mbp so I could use my old monitor and mouse when visiting home over easter. As soon as I connected my display via HDMI it started lagging. Most noticeable was the mouse lagging. Noticed that MonitorControl took 15% cpu.
I have used the app with no problem with my thunderbolt monitor.

Everything works as normal when I close the app.

**Comment by Alexandoooor** [comment]
the monitor with the problem is Asus VG248QE

**Comment by JoniVR** [comment]
Some monitors require different settings and some are unable to read the display values at all. You can try playing around with the Advanced preferences. 

The reason why you’re probably seeing stutters (at startup or device wake up) is because MonitorControl is polling (trying to read the values) the display multiple times. 

First suggestion would be changing to a longer delay, see:
https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences#longer-delay

Keep in mind that this might cause a system freeze and require a reboot. 


Second suggestion would be lowering the polling mode:
https://github.com/the0neyouseek/MonitorControl/wiki/Advanced-Preferences#polling-mode

**Comment by JoniVR** [comment]
Going to close this as there's no response and should be fixable by just lowering the polling mode setting in advanced settings. Feel free to reopen if necessary.
