### ISSUE TITLE
LG 34WK95U-W Compatibility

### ISSUE THREAD

**Issue by micstev2** [MonitorControl/MonitorControl#224]
Hi - are there any known issues with using a MacBook Pro 13 and Intel Iris Pro integrated graphics card?

This works perfectly fine with my 16 inch MacBook Pro and my LG 34WK95U-W.  But when connecting to my 2019 MacBook Pro 13 inch - Monitor Control doesn't work.  The LG shows up in the app but none of the sliders controls do anything for the monitor.

**Comment by JoniVR** [comment]
Hi, we have a Monitor Troubleshooting wiki for this:
https://github.com/the0neyouseek/MonitorControl/wiki/Monitor-Troubleshooting

This might be a good place to look first 🙂

**Comment by micstev2** [comment]
Checked all that out.  But it doesn’t answer the question/concerns listed.

**Comment by bryanlee81** [comment]
Have the same monitor and Macbook Pro 13. Having the same issue.

If I use the displayport cable, then it works but when using TB3, it no longer works.

**Comment by JoniVR** [comment]
Like it says in the wiki, it all depends on the combination of gpu, display and cable, the 16 inch probably uses the dgpu while the 13 inch uses igpu.

**Comment by micstev2** [comment]
I get it. But the responses here are pretty comical.  All I asked if anyone else if having issues.  It seems it works on most 13 MacBooks.  I would highly doubt that a 2020 13 MacBook isn’t enough to run this tool.

**Comment by sanguino** [comment]
I bought this monitor today, and at first I also have the same issues, and others related to resolution and color schemes in osx.

After updating the firmware, and configuring it to use display port 1.4 (from the OSD menu), it works as expected. Keep in mind that if the brightness is in automatic it does not allow to control it, so I deactivate automatic brightness too.

Now I'm looking for how to control it from the touch bar, because if I use the lg as output, the volume control is deactivated, and the brightness only controls the macbook monitor.

I hope it helps.

**Comment by sanguino** [comment]
431

**Comment by resilient-max** [comment]
> I bought this monitor today, and at first I also have the same issues, and others related to resolution and color schemes in osx.
> 
> After updating the firmware, and configuring it to use display port 1.4 (from the OSD menu), it works as expected. Keep in mind that if the brightness is in automatic it does not allow to control it, so I deactivate automatic brightness too.
> 
> Now I'm looking for how to control it from the touch bar, because if I use the lg as output, the volume control is deactivated, and the brightness only controls the macbook monitor.
> 
> I hope it helps.

Could you point us at the Firmware upgrade? I looked on LGs website, there is no Firmware for this screen. https://www.lg.com/us/support/software-firmware-drivers?customerModelCode=34WK95U-W&csSalesCode=34WK95U-W.AUS&category=CT10000030&subcategory=CT30014440https://www.lg.com/us/support/software-firmware-drivers?

**Comment by sanguino** [comment]
I'm using mac, catalina. The first time I open OnScreen, it ask me to upgrade the firmware. After this upgrade I can use DP 14, with full support. Last week I returned the because it is too big for my desk, sorry I can't send you any data :(

![image](https://user-images.githubusercontent.com/2077168/118373559-df019e80-b5b7-11eb-9932-53608e4ab5ed.png)
Before updtating it, the display preferences shows a reolution controller, not this scale selector.

![image](https://user-images.githubusercontent.com/2077168/118373511-95b14f00-b5b7-11eb-9a5e-b8aa50bd42fc.png)
This is the OnScreen version, hope it can help you.

**Comment by Kane610** [comment]
In my case updating the firmware broke 1.4, now I can only use 1.2 if I want 5k resolution :(

**Comment by resilient-max** [comment]
> In my case updating the firmware broke 1.4, now I can only use 1.2 if I want 5k resolution :(

Same here and LG support can't help. They argued with me for 30 minutes that there has never been a firmware update for this screen. There has been updates btw. They just don't have them as downloadable files on the website.

**Comment by sanguino** [comment]
I’m so sorry to hear that. Maybe the os version make the difference? In my case I’m in Catalina.

**Comment by resilient-max** [comment]
> I'm using mac, catalina. The first time I open OnScreen, it ask me to upgrade the firmware. After this upgrade I can use DP 1.4, with full support. Last week I returned it because is too big for my desk, sorry I can't send you any data :(
> 
> ![image](https://user-images.githubusercontent.com/2077168/118373559-df019e80-b5b7-11eb-9932-53608e4ab5ed.png)
> Before upgrading it, the display preferences shows a resolution controller, not this scale selector.
> 
> ![image](https://user-images.githubusercontent.com/2077168/118373511-95b14f00-b5b7-11eb-9a5e-b8aa50bd42fc.png)
> This is the OnScreen version, hope it can help you.

Btw. what Mac are you using. I read that it depends on the GPU too if you can use DisplayPort 1.4 or 1.2. I have the 2017 13" Macbook Pro (soon to be replaced with the upcoming 14", since the iGPU is too slow to drive this screen anyway.
If you have a dedicated GPU (15" & 16" MBPs) then it will work with DisplayPort 1.4, else only with 1.2. I have not had a test this theory, I read it somewhere else, but the writer also didn't have both Macs to test it it.

What's also strange is that you have more resolution options to choose from: 
<img width="658" alt="Screen Shot 2021-05-17 at 10 07 43" src="https://user-images.githubusercontent.com/64356730/118453776-e62fc600-b6f7-11eb-8259-f87c79eff51b.png">

I use the same OnScreenControl version: 4.58, on MacOS Big Sur
<img width="561" alt="Screen Shot 2021-05-17 at 10 09 59" src="https://user-images.githubusercontent.com/64356730/118453998-268f4400-b6f8-11eb-82a4-17546ab5739f.png">

**Comment by waydabber** [comment]
Since this appears to be a display issue and there is nothing to solve on MonitorControl's end, I'll close this issue. Feel free to open a new Issue if there is any new development or request! Thank you!
