### ISSUE TITLE
Add option to always change Display Volume upon Volume keys press

### ISSUE THREAD

**Issue by jheaton141** [MonitorControl/MonitorControl#228]
The volume adjuster does not work when Boom3D is in use. The brightness continues to work, however. 
https://www.globaldelight.com/boom/

**Comment by kikiwora** [comment]
Boom3D definitely uses a new Device, which is always selected as output, no matter what device the user tries to select.
When user selects some other device, Boom3D detects that change and automatically switches its output.

The issue with this method is that if the real output device on its own does not support native audio control, Boom3D does not give it that functionality, despite the fact that Boom3D device provides volume regulation and mute functions.

So I assume, and I'm only assuming since I have no Display with Sound capabilities to verify, that when on display output is selected (and it is when you use Boom3D), MonitorControll ignores Volume buttons.

And as a Software Engineer, I also assume that this cannot be fixed without Boom3D developer collaboration from the MonitorControll side only, cause you know, there is no real way to detect which Device is really used to output sound when Boom3D is used. 

However, I suggest bypassing this issue by adding the option for a user to "always change Display Volume upon Volume keys press".

This may not be the best possible solution, but it is quick and usable.

**Comment by JoniVR** [comment]
> So I assume, and I'm only assuming since I have no Display with Sound capabilities to verify, that when on display output is selected (and it is when you use Boom3D), MonitorControll ignores Volume buttons.

Correct, when a different audio output is selected, MonitorControl will detect if that audio device can "set its own volume", if that's the case, then it'll stop listening for volume shortcuts.

> However, I suggest bypassing this issue by adding the option for a user to "always change Display Volume upon Volume keys press".

I agree that might probably the best possible solution in this case.

**Comment by ileodo** [comment]
If someone can provide some guidance, probably I can help with this.

**Comment by jbpenrath** [comment]
Just to share my experience, I'm currently using Boom 3D and I cannot change the volume **only from keyboard function keys**. If I use the volumer slider from the MonitorControl panel, it changes the monitor volume as expected.

**Comment by waydabber** [comment]
The app checks if the current audio output has volume controls or not. If not, then it toggles the volume. It would be possible to add as an advanced setting to force listening to the keyboard no matter what or better, manually specify on which audio output should the app listen to volume keys (this would also be useful if more than one display has volume control - as probably not the location of the mouse should decide which display to control in this regard as the user probably has his speakers hooked up to one display only).

**Comment by waydabber** [comment]
This one will be dealt with here:

https://github.com/MonitorControl/MonitorControl/issues/11
