### ISSUE TITLE
Two Macs into same monitor (HDMI1 and HDMI2) - MonitorControl only works on one

### ISSUE THREAD

**Issue by michael-pesce** [MonitorControl/MonitorControl#248]
I have 2 Macs both running 10.15.5:
Mac mini (2018)
MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)

The monitor is: LG 27UD68. Both computers go into monitor via HDMI. I use the same monitor and switch between the inputs when I need to use one or the other. 

Both computers have the requested accessibility function selected. 

MonitorControl on the MacBook Pro correctly adjusts brightness (it's amazing, thank you!). 
Nothing happens when I move the slider on the Mac mini. Has no effect. 

I am baffled. Any ideas?

**Comment by JoniVR** [comment]
Can be the case due to different cables (one not supporting DDC) or different GPU's. 
Try swapping the cables and then see if the one that didn't work before works. If you have a displayport layout around try that as well. 

See: https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting

**Comment by damoen** [comment]
I am facing a very similar issue, also with Mac Mini (2018). See #265

**Comment by JoniVR** [comment]
Closing in favour of #265, let's continue tracking there.
