### ISSUE TITLE
Freezes my entire system at every launch—with default preferences

### ISSUE THREAD

**Issue by jackbrannen** [MonitorControl/MonitorControl#262]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**

Every time I launch MC with my external display plugged in, my system freezes (can't move mouse etc.). When I unplug my external display, my system unfreezes.

This persists even though I have trashed all pref files for MC, deleted the app, and redownloaded.

**To Reproduce**

1. Download MC and drag to Applications folder
2. Open
3. System freezes

**Expected behavior**

No freeze on launch

**Additional context**

The app was working with another MacBook Pro and the same display hardware and cable just a couple of days ago.

I am using default MC preferences. No modifications.

**Environment Information (please complete the following information):**
 - macOS version: 10.14.6
 - MonitorControl version: 2.0.0
 - Monitor(s): Dell P2715Q

Thanks!

**Comment by JoniVR** [comment]
What setup do you have? (MacBook) do you happen to have an Nvidia GPU?

**Comment by pkandarpa-cs** [comment]
I also have this issue. Mouse moves with extreme lag when monitor control is running. My monitors are two P2719H

**Comment by jackbrannen** [comment]
MacBook Pro (Retina, 15-inch, Mid 2015)
Intel Iris Pro 1536 MB (not honestly sure if this is Nvidia)

**Comment by JoniVR** [comment]
> I also have this issue. Mouse moves with extreme lag when monitor control is running. My monitors are two P2719H

This could be due to #49 

> MacBook Pro (Retina, 15-inch, Mid 2015)
Intel Iris Pro 1536 MB (not honestly sure if this is Nvidia)

Try going into `Settings > Advanced` and setting `Polling Mode` to `None`. Also, please post more details about the system it's not working on, specifically the GPU is probably important here.

**Comment by tierpinho** [comment]
Same issue. On Mac, 10.15.7 👇 , with latest version of this software. Very bad bug.

![Screen Shot 2020-10-12 at 08 26 19](https://user-images.githubusercontent.com/556908/95778850-a639c980-0c64-11eb-8c9a-71f5c458f35b.png)

> Try going into Settings > Advanced and setting Polling Mode to None. Also, please post more details about the system it's not working on, specifically the GPU is probably important here.

Tried this, and awaiting some more testing...

**Comment by gjuchault** [comment]
> > I also have this issue. Mouse moves with extreme lag when monitor control is running. My monitors are two P2719H
> 
> This could be due to #49
> 
> > MacBook Pro (Retina, 15-inch, Mid 2015)
> > Intel Iris Pro 1536 MB (not honestly sure if this is Nvidia)
> 
> Try going into `Settings > Advanced` and setting `Polling Mode` to `None`. Also, please post more details about the system it's not working on, specifically the GPU is probably important here.

I have one monitor (Asus VG27A), same issue. Moving Polling Mode to None fixed it.

```
MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)
1,4 GHz Quad-Core Intel Core i5
16 Go 2133 MHz LPDDR3
Intel Iris Plus Graphics 645 1536 Mo
```

**Comment by waydabber** [comment]
Please check if this issue still persists with the new 3.0.0 version. Thank you!

**Comment by jackbrannen** [comment]
Yep, it insta-froze my system again. Could this be related to my running 
SwitchResX? Third party app for custom screen resolutions.

**Comment by waydabber** [comment]
Huhh. Do you have DDC polling set to 'None'? This is the only thing that is DDC related and happens at launch time (but it should not cause a freeze).

If so then please try disabling 'Use hardware DDC control' to see if there is any change.

<img width="803" alt="Screen Shot 2021-08-21 at 18 30 34" src="https://user-images.githubusercontent.com/37590873/130328595-89473295-e1f7-4627-ae8d-d3d5cd2a2581.png">

Also:

- do you use a dock of any kind?
- what happens if you try to read or change a DDC value using ddctl? Does that cause an instant freeze as well?

Thank you!

**Comment by jackbrannen** [comment]
I’m not able to even get to this since my computer freezes instantly 
when the app opens.

**Comment by waydabber** [comment]
Ohh, I see. We should probably add a "Safe mode" startup option that skips DDC checks if previously this caused issues. 

Also, could you please give a little more detail on the following:

- Does the app cause a freeze even if there is no external display connected?
- What kind of connection/cabling do you use?
- do you use a dock of any kind? 
- what happens if you try to read or change a [DDC value using ddctl](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)? Does that cause an instant freeze as well?

Also, can you send me the preferences file folder of your app `me.guillaumeb.MonitorControl.plist`? It is located under your user's Library folder (in Finder select the `Go` menu, press the `Option` key on the keyboard and then click on `Library`), where there is a `Preferences` folder. In this `Preferences` folder you should find this file.

Thank you!

**Comment by waydabber** [comment]
Hi,

Here is an [unsigned test build](https://www.dropbox.com/s/w1md5rjyll0lsyo/MonitorControl.zip?dl=1). This requires you to click 'Open Anyway' in Preferences/Security. The source of this build [is here](https://github.com/MonitorControl/MonitorControl/tree/temp/debug) - if you don't trust in unsigned builds and want to build it yourself.

With this version, if you press Shift during app startup, you'll see the following alert:

<img width="372" alt="Screen Shot 2021-08-31 at 15 30 45" src="https://user-images.githubusercontent.com/37590873/131511392-44d195e6-0b79-4d39-b3bb-f6aeaf94192a.png">

This will reset all preferences and also disable DDC read which probably causes the freeze. After this you can set Polling to 'None' in the Advanced section of Displays

**Comment by jackbrannen** [comment]
Hey @waydabber, you are so kind to offer all of this troubleshooting help. I started following your steps above and hit issues installing ddcctl. Truthfully this is more trouble that it's worth to me at this point—I hope to get a new M1 MBP in a few months and can wait until then.

**Comment by waydabber** [comment]
All right, no problem. It was beneficial anyway to solve the issue of making a way to start the app if initial DDC read caused an obstacle by introducing safe mode.

I close this issue then now. :)
