### ISSUE TITLE
Automatically adjust external display based on internal display + Touch Bar support

### ISSUE THREAD

**Issue by funbben** [MonitorControl/MonitorControl#27]
It would be nice to be able to use the mac "auto adjust brightness" to set the brightness of external display automatically

https://i.stack.imgur.com/eYQuM.png

**Comment by the0neyouseek** [comment]
Hi @funbben,

Thats a great idea but would be quite difficult to implement because this feature depends on the ambient light sensor (located next to the camera) of your Macbook Pro/iMac and not all external screen have one.

I'll leave this issue open for now to see if anyone has a better idea about tackling this.

PS. We could, for exemple use the one present on your MBP/iMac if we have one, but I'm not sure how. I'll look into it.

**Comment by funbben** [comment]
The idea was to use mac internal sensor and apply same setting as Mac display

**Comment by rowanalex123** [comment]
Hammerspoon provides the lux reading from the ambient light sensor on Macs

**Comment by retrography** [comment]
@rowanalex123 Have you actually tried that? The function only returns an error for me -- which is a -1 (on MacBook Pro 2016).

**Comment by rowanalex123** [comment]
I tried it now. It returns -1 for me as well on a 2017 Mac pro

**Comment by the0neyouseek** [comment]
Hi, first of all sorry for the late response.
I'll try to work on this feature this week-end.

**Comment by jcastro** [comment]
Just something that might be of interest. The new LG 2019 Ultrafine 5k is finally using the light sensor (see https://twitter.com/jonatan/status/1167163794281455616) so maybe there's a chance to use that information to automatically change others' display brightness (probably with a configurable offset for the value)

**Comment by jcastro** [comment]
Another interesting fact, looks like now even the older LG Ultrafine 5k that didn't have the auto-brightness working now it's enabled if you are on Catalina.

**Comment by rshev** [comment]
Just found this app, mainly because I'd like to have different brightness during the day and in the evenings, and immediately thought of this idea. Has anyone had any luck reading ambient light values? I might help, I do swift for a living.

**Comment by dmatora** [comment]
There is an open source console app that allows automatically changing brightness on old UltraFine 4K/5K monitors that don't have ambient light support built into maOS.
https://github.com/qvacua/ultrafine-auto-brightness
I own old UltraFine 4K monitor and would love to see it's ambient light sensor support in MonitorControl

**Comment by sraka1** [comment]
Feature request is still pending. Commenting so it's not auto-closed.

**Comment by waydabber** [comment]
This might be a bit out of focus for MonitorControl right now but still we might add this function in the future as apparently this is among the core ideas all the way back to 2018. :)

There is an app called [Lunar](https://lunar.fyi) however made by @alin23 that already does this thing for those who are impatient for a solution.

**Comment by alin23** [comment]
Thanks @waydabber for letting people know about Lunar! Indeed, Lunar has Sync mode which takes advantage of **Automatically adjust brightness** by syncing the already adjusted brightness of the built-in display to the external monitors.

The problem with reading the sensor directly is that:
1. It's not possible at all on Intel Macs (or at least I couldn't find a way to do it, the I/O Kit registry doesn't seem to expose any kind of lux or raw value)
2. It's very hard to map the lux value to a brightness value when each single external monitor has its own lightness (nits) range
3. You'll get more accurate results by reading the already adapted brightness of the builtin display because the system has an internal representation of the lightness curve of the display and can map it very well to the lux readings of the sensor.

If anyone is interested in reading the lux value on M1 Macs, because that is possible there, here is how to retrieve it from the command line:

```sh
ioreg -r -c AppleSPUCT720 | awk '/CurrentLux/{print $4}'
```

Doing that in Swift would require iterating the I/O Kit registry by matching the class `AppleSPUCT720` and then extracting the `CurrentLux` property. Probably something like this:

```swift
#!/usr/bin/env swift

import IOKit
import Foundation

func getLux() -> Float? {
    let sensor: io_service_t
    if #available(macOS 12.0, *) {
        sensor = IOServiceGetMatchingService(kIOMainPortDefault, IOServiceMatching("AppleSPUCT720"))
    } else {
        sensor = IOServiceGetMatchingService(kIOMasterPortDefault, IOServiceMatching("AppleSPUCT720"))
    }

    guard sensor != 0 else {
        return nil
    }

    guard let luxProp = IORegistryEntryCreateCFProperty(sensor, "CurrentLux" as CFString, kCFAllocatorDefault, 0),
          let lux = luxProp.takeRetainedValue() as? Float
    else { return nil }

    return lux
}

print(getLux() ?? -1)
```

**Comment by waydabber** [comment]
Wow @alin23 thanks for the detailed info! I wanted to go on the route of reading the internal display brightness (as that will also help on an other request, namely the use of the MBP touch bar slider for brightness change - I think we have a similar situation there that we can only infer the selected brightness only from the display's brightness itself, but I am not entirely sure, since I don't have an MBP myself and hate the idea of the touchbar. :))

_But there is a rather long list of other accumulated issues to be dealt with so I am afraid this one does not have the highest prioirty at the moment._

**Comment by waydabber** [comment]
Just some info about the progress regarding this issue:

- [x] There is now polling for the internal screen + sliders are updating based on change which was implemented when solving https://github.com/MonitorControl/MonitorControl/issues/198. This works nicely whenever the ambient light sensor kicks in or the touchbar slider is used. This is a foundation to have the brightness replicated among other displays.
- [ ] Some other things are needed until proper synchronization can be done. These are #310, #418 and #570. These are interlocked issues and I am in progress of making it work.
- [ ] Once the above are done, this and #334 will logically follow.

**Comment by waydabber** [comment]
Brightness change synchronization from Built-In and Apple displays to other displays is now added. This makes Touch Bar, Ambient light sensor, Control Center and System Preferences induced changes affect all displays. Synchronization is not direct, but only changes are replicated - the user can intervene and adjust at any time.

https://github.com/MonitorControl/MonitorControl/discussions/596
