### ISSUE TITLE
Not working with LG 38WN95-C

### ISSUE THREAD

**Issue by SlawaGurevich** [MonitorControl/MonitorControl#277]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Issue Description**
So the tool is not working with the new LG 38WN95-C. I can control neither the brightness nor the volume. (See screenshots bellow.) I also tried with the ddcctl tool, screenshot attached as well. Not sure about the "Failed to poll the display". Couldn't find much on Google about this error.

**Expected behavior**
Well, the tool should work with this monitor. I checked, whether it supports control over DDC, and according to the manufacturer, it does.

**Screenshots**
![Settings in app](https://drive.slawagurevich.com/displaysettings.png)
![Tried with DDC](https://drive.slawagurevich.com/ddc.png)

**Environment Information (please complete the following information):**
 - macOS version: 10.15.4
 - MonitorControl version: 2.0.0
 - Monitor(s): LG 38WN95-C
 - Mac model: Macbook 16"
 - Monitor Cable(s)/Connection(s): (e.g. DisplayPort) Thunderbolt (Can you even do DDC over TB? 🤔) The cable is the original one that came with the monitor, not some no-name from Amazon, so I hope this should be fine.

**Comment by JoniVR** [comment]
I have the new LG 38GN950 myself now (which is very close to your model) and it works perfectly for me.

I'm using thunderbolt (actually displayport through an eGPU, but it works directly too). My first suggestion would be trying a different cable/connection anyways (I know this is probably not what you want to hear but it has the highest succes rate).

Polling is not the same as sending a command. Polling is trying to read values, in some cases, reading will fail but sending commands will work, so definitelytry sending a command too. Check out the wiki for more information on this.

**Comment by SlawaGurevich** [comment]
Hi @JoniVR ,

thanks for the reply. I finally got around to testing this.

So I got another Thunderbolt 3 cable, the only one I had lying around actually, the one from my MacBook to connect it to power. However, the monitor didn't turn on at all, so I assume this cable won't work. I'll try getting another TB3 cable, although I'd rather not buy another one just to find out it wasn't a problem with the cable.

As for sending commands, I tried out some from the help menu, but the display didn't respond:

![image](https://user-images.githubusercontent.com/13917864/94364420-55a16880-00c9-11eb-93c3-7bb7bb7e52cb.png)

It is still listed as unknown, even in 2.1.0. Shouldn't it at least be recognized by the app for it to be usable? With the Vendor and Hardware ID being public and all...

**Comment by wojciechczyz** [comment]
Mac book power cable is not thunderbolt, it does not has thunder logos on it either.

**Comment by GM-Alex** [comment]
@JoniVR I have also a LG 38GN950 and a LG 34UC98-W. Since I start using the LG 38GN950 and replaced a LG 24EB23 with the LG 38GN950 Monitor Control freezes and my macbook gets super slow. The mouse has micro freezes if it's moving and Monitor Control doesn't react until I kill it. I'm using a Caldigit TS3 Dock, the LG 34UC98-W is connected via Display Port and the LG 38GN950 via a Thunderbolt to HDMI cable. Is there any debug information I can you provide to fix this issue?

**Comment by waydabber** [comment]
@SlawaGurevich - since ddcctl can't control the display as well (MC uses DDC.swift but it seems neither software is working), probably there is not much we can do on MonitorControl's end with this as this is a hardware issue. :( Sorry about that.

@GM-Alex - please try the new 3.0.0 version as this has a slightly different logic to detect displays and handle configuration changes and please report back if this solves the issue or not. Thank you!

**Comment by waydabber** [comment]
I'll close this issue for now but please feel free to comment if there is anything we can do. If the issue persists, we can reopen this issue! Thank you!
