### ISSUE TITLE
Cannot set any of the controls from 1 to 4, it jumps from 0 to 5

### ISSUE THREAD

**Issue by teejay-87** [MonitorControl/MonitorControl#278]
As per the title of the issue, on my monitor Asus MX27UC (connected on USB-C), I cannot set brightness nor contrast (nor volume) to a value from 1 to 4. The slider jumps directly from 0 to 5.

![Registrazione schermo 2020-08-16 alle 23 42 17](https://user-images.githubusercontent.com/17051981/90344507-bcd3f380-e01a-11ea-9574-f8b1173fa304.gif)

Not sure this is related to my specific monitor or not.

**Comment by JoniVR** [comment]
I'm seeing this too using the sliders, I also tested it on the other end (upper limit) and seem to be having the same issue, could you test if this happens for you too?

**Comment by teejay-87** [comment]
> I'm seeing this too using the sliders, I also tested it on the other end (upper limit) and seem to be having the same issue, could you test if this happens for you too?

I confirm.

I would add that it's not so "minor", especially at night ;-)

**Comment by nabsher** [comment]
I'm seeing the same issue with the volume keys from my keyboard.  On my LG HDR 4K monitor the volume jumps as follow 0, 6, 13, 19, 25....etc.  Can provide any output needed to help diagnose.  Thanks!

**Comment by giosoftware** [comment]
I confirm on my LG HDR 4K

**Comment by dimaqq** [comment]
Also LG here, 32UN880-B (32-inch, 4K, with a nice arm)...
When dragging the volume slider very carefully, I can set `0, 4,5,6,7....` Which is odd but actually OK-ish for me.

What bugs me though, is if I use keyboard volume buttons, I can only set `0, 6, 13, 19, ...` and on this monitor, the `6→13` is a a big jump in volume. Measured in youtubes, `6` @ 100% if roughly the same as `13` @ 20% volume.

I kind wish it was possible to remap the curve/steps (both for dragging as well as for keyboard)... or maybe find some reasonable progression that works for most monitors?

**Comment by NatachaH** [comment]
Bonjour,

Je suis actuellement en vacance du du 18 décembre 2020 au 5 janvier 2021 et je répondrai à votre mail à mon retour.
Pour les urgences, vous pouvez m'appeler au 078 625 77 42

Meilleures salutations et de joyeuses fêtes de fin d'année.

Natacha Herth

**Comment by JoniVR** [comment]
Removed comment because personal data, seemed accidental.

**Comment by waydabber** [comment]
Hey guys @teejay-87 and @JoniVR , the original issue is totally intentional, this snippet of code does this:  

```
    let closest = (value + snapInterval / 2) / snapInterval * snapInterval
    if abs(closest - value) <= snapThreshold {
      value = closest
      slider.integerValue = value
    }

```

This is currently configured to snap the slider to 0, 25, 50, 75, 100 when the knob is in vicinity. It might be annoying at 0.

Question: should we get rid of this?

About the isse with some displays being way too loud too quickly, this issue will solve that whenever it is implemented: https://github.com/MonitorControl/MonitorControl/issues/310 . This could also be extended with a "gamma curve" option both for brightness and volume.

**Comment by OliverS79** [comment]
I like the gamma curve option!

**Comment by waydabber** [comment]
Hi all, I'll close this issue for now but please feel free to comment if there is anything we can do or if you'd like this snapping behavior to go. If the real problem is not that the slider snaps to zero or that the volume increase is too steep, I recommend following this issue:

https://github.com/MonitorControl/MonitorControl/issues/310

**Comment by waydabber** [comment]
I reopen this issue and will add an Advanced setting so the snapping could be turned on/off.

**Comment by waydabber** [comment]
You'll have to disable slider snapping in the upcoming 3.1.0 here for finer control:

<img width="803" alt="Screen Shot 2021-09-07 at 16 53 08" src="https://user-images.githubusercontent.com/37590873/132366120-1ee7b581-127d-4ef4-adb5-0b7d4633fc63.png">

**Comment by teejay-87** [comment]
Thanks for adding this.
Honestly I'd remove the snap at 0% and 100%.
They are totally useless, you can just drag the slider to the left or to the right.

**Comment by waydabber** [comment]
Hi @teejay-87 - you are probably right, but this is like this for historical purposes and also its feels kinda symmetrical (?) to have snapping at the ends if you have snapping at other places. Maybe snapping should be disabled by default though.

The more important point is that for most the snapping is not the real problem but the fact that the volume and brightness curve of the display is uneven - it is common that most of the visible changes in brightness happen between 0-10% of the curve and also, the volume curve can be such that beyond 20% starts the too loud category, so the actually sensible range to deal with is the 10-20% of the slider. The snapping is problem in this context since it takes away almost a quarter of the area where the user needs fine control. This problem really could be solved by introducing a setting to have an upward opening parabola/exponential curve for brightness with a setting for a curve factor + an upper bound setting for volume (which allows the remapping of the the sensible maximum to 100%).

**Comment by foss-** [comment]
Naive question: Besides the question of snapping, why not allow users to use the increments the external monitor offers to increase | decrease volume using the hardware volume control keys?

Snapping is one aspect but the curve and points on curve used is the other factor. And while we can discuss changing the curve, for me, the issue would be solved if I could just use the increments used by the external monitor one by one, which currently is not possible, making volume control hard to use with unsatisfactory results in the lower volume percentages where fine grained control really is needed (as explained by you above).

**Comment by waydabber** [comment]
hi @foss- , you can already do that by pressing shift+option+volume up/down! You are right in that feature is not heavily promoted... :)

**Comment by JoniVR** [comment]
An easy fix for this that I've seen mentioned before would be a setting where +1 increments are the default (basically reversing how it works)

**Comment by waydabber** [comment]
We could add such a setting in the Keyboard pane under Preferences (as with the menu items in 3.1.0 a new Menu tab was needed, for keyboard customization and other keyboard related stuff we should reintroduce Keyboard pane).

I added it as a new Feature Request here: https://github.com/MonitorControl/MonitorControl/issues/571 :)

**Comment by waydabber** [comment]
Fine control for volume option is now added - see #571
