### ISSUE TITLE
CTRL + Volume for Headphone Jack / Internal Volume

### ISSUE THREAD

**Issue by chrisspiegl** [MonitorControl/MonitorControl#281]
Add the ability to change the internal and external volume with modifier keys.

It's awesome that V2.0 already added support to change the Brightness of Internal and External Monitors. I would love to see this extended to the Volume Functionality, I use the headphone jack to send audio to a stereo system for music playback, but all other audio is going through my monitor.

The modifier with "CTRL + Volume Keys" would be an awesome fix (just like brightness works).

Warm Regards,
Chris

**Comment by pointmax** [comment]
does changing the brightness individually work? It doesn't seem to work for me...
I can only change the brightness for both displays (macbook + monitor) simultaneously

**Comment by waydabber** [comment]
Hi @pointmax - it should work - depending on where your mouse is situated (in version 3.0.0). Also you can use ctrl+brightness keys to control the internal display specifically.

Using CTRL+Volume Keys is a bit different since if there are several audio devices, the app will not know which one to fall back to in this case (unlike for internal displays which is easily identifiable). This would therefore require a more extensive solution where you could define which shortcut key should control which audio device - which is not really in the scope of MonitorControl (but might be for an other app).

Because of this I'll close this issue. If you don't agree with this answer or you have a suggestion on how this should work and still fit the profile of MonitorControl, please let me know! Thank you!
