### ISSUE TITLE
When Terminal is active, only built-in display brightness is adjusted

### ISSUE THREAD

**Issue by joseph-levine** [MonitorControl/MonitorControl#282]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Describe the bug**
When Terminal is the active application on the external display, the built-in display brightness is adjusted instead of the external.

**To Reproduce**
1. Go to 'Terminal' (Make sure it's the focused application)
2. Use the brightness keys to increase or decrease brightness

**Expected behavior**
The external display brightness would change.

**Screenshots**
N/A

**Additional context**
N/A

**Environment Information (please complete the following information):**
 - macOS version: 10.15.6
 - MonitorControl version: 2.0.0
 - Monitor(s): Dell U2713HM

**Comment by JoniVR** [comment]
I'm unable to reproduce this, you're certain that the external monitor was "focussed" here? Because there's currently a bug where the external monitor will not be controlled if internal is "active/foccused" (when you click in it).

**Comment by clheppell** [comment]
I've spotted this issue - only affecting the brightness keys, via the icon it still works - but I didn't need terminal to be in focus.

Seemed to me to be that when Terminal is running (but does not necessarily have an open window) and `Secure Keyboard Entry` is enabled in Terminal, then brightness keys only affect built in Mac monitors.

Turn off `Secure Keyboard Entry` and it works again, so I assume it's caused by the fact `Secure Keyboard Entry` is meant to  prevent key loggers etc and so MonitorControl is unable to receive the key presses?

**Comment by JoniVR** [comment]
@clheppell That makes a lot of sense, I'll try it out to confirm when I get time 😊

**Comment by joseph-levine** [comment]
I just tested and `Security Keyboard Entry` was it!

Thanks
