### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by wangweiwei104** [MonitorControl/MonitorControl#284]
**Checklist**

- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
This software can control the brightness, but there will be a splash screen when using HDMI to connect the monitor

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Environment Information (please complete the following information):**
 - macOS version:10.15.6
 - MonitorControl version:2.0.0
 - Monitor(s):KOIOS K2719U
 - Monitor Cable(s)/Connection(s): HDMI

**Comment by JoniVR** [comment]
Can you define "splash screen"? Is it a black screen or?

**Comment by simphide** [comment]
I think he means the monitor settings visual

**Comment by waydabber** [comment]
Since this seems to be a monitor display (probably the display's own OSD appears) I'll close this issue. About the OSD appearing there is not much we can do. Some displays allow the OSD to be disabled but this is not supported uniformly (we had this for volume as "Hide OSD" in the past but for some folks this command permanetly disabled the OSD, for others it made it flicker and some others didn't help at all).
