### ISSUE TITLE
Volume control for select AV receivers with digital audio connection (HDMI or optical)

### ISSUE THREAD

**Issue by MaartenBorsje** [MonitorControl/MonitorControl#287]
Monitor control already works for controlling the audio via a dock like the Celdigit TS3+. But it doesn't work for audio via Optical wire. I like to see a way to get that working to

**Comment by waydabber** [comment]
Hi, you can't control audio levels via optical since an external receiver/amplifier is involved. I have a solution that controls Yamaha AV receivers directly (via local network), this might be done for other receivers. I plan to add such a functionality to MonitorControl in the future (at least to control my Yamaha receivers but will try to do it in a way that the implementation will be open for other receivers which have some sort of open protocol for control).

**Comment by MaartenBorsje** [comment]
> Hi, you can't control audio levels via optical since an external receiver/amplifier is involved. I have a solution that controls Yamaha AV receivers directly (via local network), this might be done for other receivers. I plan to add such a functionality to MonitorControl in the future (at least to control my Yamaha receivers but will try to do it in a way that the implementation will be open for other receivers which have some sort of open protocol for control).

Nice. Then I gonna have a look at the api for the Heos by Denon receivers.

**Comment by waydabber** [comment]
Meanwhile you can use this free Hammerspoon script for Yamaha AV control (you can disable the monitor DDC control part of the script as MonitorControl does this better). I made this script last summer and use it daily to control my Yamaha AVs from my Mac via the native volume keys. It uses [showddc](https://github.com/waydabber/showosd) to show the macOS volume OSD. Works fine alongside MonitorControl.

https://gist.github.com/waydabber/3241fc146cef65131a42ce30e4b6eab7
