### ISSUE TITLE
DELL S2721QS and MacBook Pro suddenly not working

### ISSUE THREAD

**Issue by allofyx** [MonitorControl/MonitorControl#337]
Hi! It is a great app! It was working fine with both functions, all of the suddenly the Monitor control is out of work, when I try to open it, I cannot even use the monitor? What should I do?

**Comment by ColtonIdle** [comment]
I just got the S2721QS and everything works fine with monitorcontrol. Can you explain more about what doesn't work?

**Comment by allofyx** [comment]
> I just got the S2721QS and everything works fine with monitorcontrol. Can you explain more about what doesn't work?

thanks for the reply, I change the cable and the USB ports, it worked as usual.

**Comment by ColtonIdle** [comment]
@allofyx Cool. We can probably close this then.

**Comment by allofyx** [comment]
> @allofyx Cool. We can probably close this then.

another question. When you turn on the RGB mode on your S2721QS, will the screen be green?(I have this problem using MacBook Pro)

**Comment by ColtonIdle** [comment]
RGB mode? Can you tell me where to find that? 

I just looked under Color > Input Color Format  I already have it set to RGB by default?

**Comment by allofyx** [comment]
> RGB mode? Can you tell me where to find that?
> 
> I just looked under Color > Input Color Format I already have it set to RGB by default?

Thats it! My default is YPbPr, but when I switch to RGB the monitor turns into green. Are you using the monitor with a Mac or windows?

**Comment by ColtonIdle** [comment]
With an imac, using type c to displayport. but the imac is in mirror mode (my imacs screen broke basically so I'm using this as a primary monitor with an imac... which is weird, but whatever)

What kind of macbook pro are you using and what cables? I can try something else. 

Question for you since we're chatting. Are the left and right edges just ever so slightly blurry? Its driving me insane. It looks like theres a plastic film on the entire display.

**Comment by ColtonIdle** [comment]
just for shits. I changed to YPbPr and the entire screen went green. lol I wonder if theres a firmware update or something. anyway. I think I'm returning it

**Comment by allofyx** [comment]
> just for shits. I changed to YPbPr and the entire screen went green. lol I wonder if theres a firmware update or something. anyway. I think I'm returning it

there was no blurriness for me. Our problem seems to be Reversed. I am using the 2020 13inch MacBook Pro (not the m1). I  heard the green is because the Mac detects the monitors as TV

**Comment by ColtonIdle** [comment]
I have a 2020 macbook pro. What cable are you using? I'll try it

**Comment by allofyx** [comment]
> I have a 2020 macbook pro. What cable are you using? I'll try it

I am using the hdmi which came with the monitor and a adapter. I bought a DP cable its still on the way. if you returned the S2721QS, what would you get instead?

**Comment by ColtonIdle** [comment]
fell in love with the 27inch 5k imac display honestly and now I'm kinda pissed that nothing like that really exists. =) but I've got a few ideas. I think I'm going to go the lg ultrafine lineup route. The lg 5k "made for mac" seems really nice, but I want an hdmi port too... so I might go for that.

**Comment by allofyx** [comment]
> fell in love with the 27inch 5k imac display honestly and now I'm kinda pissed that nothing like that really exists. =) but I've got a few ideas. I think I'm going to go the lg ultrafine lineup route. The lg 5k "made for mac" seems really nice, but I want an hdmi port too... so I might go for that.

I agree thats the one. The only disadvantage is the price lol

**Comment by ColtonIdle** [comment]
I was thinking of skipping the 5k because of three reasons. 1: Price tag 2: Only a single input (i'd like to be able to switch between a computer and playstation rather quickly) 3: Year released. Probably doesn't matter but its a 2016 monitor. surely some things could have been improved since then?

Edit: Okay. I looked the 5k one actually has a model that's one letter different and that was released in 2019. I need to see if I could get a desk splitter/switch so I could go between a playstation with hdmi.

but anyway. I'm going to pickup the 27inch 4k ergo monitor at some point this week. plenty of ports on the back and im hoping some of that 5k ultrafine display tech makes it into the 4k ergo which was released in 2020 so theyre fairly new which is nice. If that ends up being crappy, I'm just going to buy the 5k one I guess. I can't live going from 5k to a subpar blurry 4k. =)

**Comment by ColtonIdle** [comment]
@allofyx alright. grabbed my macbook pro and went type c to hdmi and... what do you know. YPbPr by default. Changing to rgb made everything green and purple. so it looks like a displayport vs hdmi default thing?

**Comment by allofyx** [comment]
> @allofyx alright. grabbed my macbook pro and went type c to hdmi and... what do you know. YPbPr by default. Changing to rgb made everything green and purple. so it looks like a displayport vs hdmi default thing?

there are ways to fix it, but I updated to Big Sur.. waiting for new solution. meaning while YPbPr is not too bad

**Comment by unclerayray** [comment]
Yep. Can confirm. I'm on Dell S2419H with HDMI cable and I'm experiencing the same issue where when I try to adjust the volume, my screen just went green and I lost the audio output.
