### ISSUE TITLE
Implementation MCCS via USB (EIZO)

### ISSUE THREAD

**Issue by gustavneustadt** [MonitorControl/MonitorControl#364]
I have a EV2785 and sadly MonitorControl doesnt work for me. I had contact with EIZO support and they confirmed to me that they do not build DDC/CI controllers in their monitors anymore. They seem to use their own proprietary windows software. (#351)

I found [dccutil](https://github.com/rockowitz/ddcutil/) supports the MCCS protocol which is necessary (?) for monitors from Eizo. It communicates not via hdmi/dp but via usb with the monitors to control them. I didnt tried it, because I was not able to build it on my mac.

Would be nice to see a implementation of this.

**Comment by waydabber** [comment]
You are right, this could be a useful feature. I'll try to add this in the future (but no promises).

"Alternatively, some monitors (e.g. Eizo ColorEdge, Apple Cinema) provide a USB interface to the VCP, as described in the USB Monitor Control Class Specification. ddcutil can communicate with these monitors over USB instead of I2C."

**Comment by waydabber** [comment]
For future reference - ddcctl seems to use this to detect such displays:

https://github.com/rockowitz/ddcutil/blob/39ce66b42305b304816d635b42a5b38ce280e2dd/src/usb/usb_displays.c#L693-L743

Also, for Apple branded external displays standard DisplayService calls should work (this is now limited to the internal display only).

@gustavneustadt - a question: does the built in MacOS brightness slider control the Eizo display? Or even though it implements a similar protocol to Apple's Cinema display it is not being controlled by the OS? Thank you!

**Comment by alin23** [comment]
One can easily test if DisplayServices works for their monitor using the Lunar CLI.

1. Install the CLI from the menu bar as seen here: https://lunar.fyi/#cli
2. Get the Serial/UUID of the display you want to test using this command:
```sh
lunar displays | egrep '^\s+Name:|Serial:'
```
3. And then test `DisplayServicesSetBrightness` and `CoreDisplay_Display_SetUserBrightness` using the following commands (run them one by one to see which one works)

##### Set brightness `20` for UUID `37D8832A-2D66-02CA-B9F7-8F30A301B230` using `DisplayServices`
```sh
lunar display-services SetBrightness 37D8832A-2D66-02CA-B9F7-8F30A301B230 20
```

##### Set brightness to `20` for UUID `37D8832A-2D66-02CA-B9F7-8F30A301B230` using `CoreDisplay`
```sh
lunar core-display SetUserBrightness 37D8832A-2D66-02CA-B9F7-8F30A301B230 20
```

**Comment by waydabber** [comment]
Thanks @alin23 !

@gustavneustadt - please let us know if you have the results. Thank you!

**Comment by gustavneustadt** [comment]
Thank you very much! I am currently on vacation but will try it for sure.

**Comment by deg0nz** [comment]
Hi,

just a qick feedback:

I was able to test the Lunar stuff described by @alin23 with a MacBook and an Eizo EV2785 connected via USB-C. Lunar is NOT able to change the brightness of the display.

**Comment by waydabber** [comment]
@gustavneustadt,

I meant the Dispaly Brightness slider in Big Sur's control center. But if the keyboards don't work, then probably EIZO displays are not regarded the same way as Apple displays even though they use a similar protocol.

<img width="338" alt="Screen Shot 2021-08-25 at 18 41 11" src="https://user-
images.githubusercontent.com/37590873/130830955-34e6499d-9f49-45b1-9f8a-ff94396e7987.png">

@deg0nz,

thanks for the feedback.

We should probably divide this issue into two - supporting Apple displays is easy by using DisplayServices while supporting MCCS via USB is an entirely different thing to do.

**Comment by waydabber** [comment]
Apple branded displays will be handled here:

https://github.com/MonitorControl/MonitorControl/issues/539

**Comment by waydabber** [comment]
For those with Apple displays, there is a link to a test build with proper support in this issue: https://github.com/MonitorControl/MonitorControl/issues/539

Unfortunately this will not work for EIZO displays.

**Comment by waydabber** [comment]
I am afraid MCCS over USB probably won't happen unless somebody who actually has an EIZO display that supports this protocol and has the ability to port the relevant codes from [this](https://github.com/rockowitz/ddcutil/tree/39ce66b42305b304816d635b42a5b38ce280e2dd/src/usb) over to Swift/macOS does the job.

(Of course if somebody is willing to donate a display like this to the cause then the core dev team can work on it as well but even then it's gonna be a lot of work so I don't really see this as a feasible alternative).

I'll convert this issue into a discussion since it makes no sense to have this sit here forever while letting the stalebot eat the issue does not seem to be the proper way to handle this either.
