### ISSUE TITLE
LG 27MP89HM

### ISSUE THREAD

**Issue by ManuISEN** [MonitorControl/MonitorControl#405]
Hello,

I would like to thank you first for your amazing work.

**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [x] I have updated MonitorControl to the latest version

**Describe the issue**
I'm not able to change either volume nor brightness.

**Expected behavior**
As you can see on [its specification page](https://www.lg.com/uk/monitors/lg-27MP89HM) my monitor is capable of DDC (tried [ddcctl](https://github.com/kfix/ddcctl) as suggested on the [wiki page](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting) but didn't work too).

**Screenshots**
![image](https://user-images.githubusercontent.com/22475882/111026480-c1af2900-83ea-11eb-8464-10714b30573b.png)
**Environment Information:**
 - macOS version: Big Sur 11.2.3
 - MonitorControl version: 2.1.0
 - Monitor(s): LG 27MP89HM-S
 - Mac model: Mac mini (2018)
 - Monitor Cable(s)/Connection(s): HDMI

**Comment by ManuISEN** [comment]
up

**Comment by waydabber** [comment]
Hi @ManuISEN - as I see you are using a 2018 Mac Mini via HDMI. Unfortunatelly 2018 Mac Minis and 2020 M1 Minis block DDC communication via HDMI. You'll need a cable that uses USB-C on these devices. Sorry to say, but there is no known workaround for that at the moment unfortunatelly, that's why ddctl does not work either. :(

I'll close this issue but let me know if I can be of any help! Thanks!

**Comment by waydabber** [comment]
Great! :)
