### ISSUE TITLE
Disable BezelUI for Volume Info (LG Issue)

### ISSUE THREAD

**Issue by dimitrij2k** [MonitorControl/MonitorControl#480]
**Checklist**
- [x] I have searched for existing issues
- [x] I have looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [x] I have updated MonitorControl to the latest version

**Is your feature request related to a problem? Please describe.**
Changing Volume on a LG Monitor bring the Monitor OSD on Top. Hiding OSD cause flickering of the OSD.

**Describe the solution you'd like**
Is it possible to disable the BezelUI (Info Popup from OSX) for Volume changes or completly disable it?

**Additional context**
When the external Monitor is not connected, the BezelUI should be enabled - when external Monitor is connected, just Volume Info should be disabled, because the Monitor UI come into the game. 

- macOS version: 11/5
- Mac model: MacBook Air (2021)
- MonitorControl version: 3.0.0-b1
- Monitor(s): LG 32UN880
- Apple Silicon/M1 (yes or no): yes

**Comment by waydabber** [comment]
I'll add this to the next version. I agree that the old "Hide OSD" implementation is making no sense - it is very slow, makes OSD flicker and very difficult to even understand what is happening. There are even some issues opened because of this. I'll change "Hide OSD" to "Disable macOS Volume OSD" something like this:

<img width="803" alt="Screen Shot 2021-08-16 at 21 00 46" src="https://user-images.githubusercontent.com/37590873/129615918-4c8edf40-12c1-4cb5-907f-6bca00d12c93.png">

So if an user with an LG display doesn't want both OSD-s to show up he'll have the option the let the display do it's thing only.

**Comment by dimitrij2k** [comment]
Perfect, thank you!!! 

By the way, osx make always huge jumps when changing volume. Is it possible, to make it the default setting, to make just "one step" jumps. Like changing volume with pressed option+shift keys.

**Comment by waydabber** [comment]
Hi, I'll add an option to limit max volume in one of the future releases - this should take care of the "huge jumps" as the new max will be a a lower value. 

See this: https://github.com/MonitorControl/MonitorControl/issues/447

**Comment by waydabber** [comment]
Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

**Comment by dimitrij2k** [comment]
> Hi, we have relased the [3.0.0 version](https://github.com/MonitorControl/MonitorControl/releases/tag/v3.0.0-rc1). Could you please test if this issue is resolved and report back? Thank you!

Works wonderful! Thank you.
