### ISSUE TITLE
No use for my dell u2720qm & M1 mac mini through usb-c cable

### ISSUE THREAD

**Issue by FRS666** [MonitorControl/MonitorControl#490]
**Checklist**

- [ ] I have searched for existing issues
- [ ] I have looked through [the Monitor Troubleshooting wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [ ] I have updated MonitorControl to the latest version

**Describe the issue**
A clear and concise description of the problem.

**Expected behavior**

**Screenshots**
<img width="982" alt="截屏2021-07-31 下午6 07 13" src="https://user-images.githubusercontent.com/75195948/127736532-3fba92d6-9af3-4d70-8240-54ee08210eed.png">

**Additional context**

**Environment Information (please complete the following information):**

- macOS version:
- MonitorControl version:v3.00-beta2
- Monitor(s):dell u2720qm
- Mac model:M1 mac mini
- Monitor Cable(s)/Connection(s): (e.g. DisplayPort)usb-c cable
- Apple Silicon/M1 (yes or no):yes

**Comment by waydabber** [comment]
Hey @FRS666 - can you please try one of the recent betas (beta5, beta6) to see if any of them work? Thank you!

https://github.com/MonitorControl/MonitorControl/releases

**Comment by FRS666** [comment]
Both beta 5&amp;6 work, great job bro.
but I see a new bug in beta6
the newly added Contrast adjustment cannot work well.
sometimes it just can't work, sometimes may cause the screen goes dark(It's not completely black, but the brightness has decreased)


thanks again for the great app, I enjoy a lot.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MonitorControl/MonitorControl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月12日(星期四) 凌晨4:29
***@***.***&gt;;
抄送:&nbsp;"Nana ***@***.******@***.***&gt;;
主题:&nbsp;Re: [MonitorControl/MonitorControl] No use for my dell u2720qm &amp; M1 mac mini through usb-c cable (#490)





 
Hey @FRS666 - can you please try one of the recent betas (beta5, beta6) to see if any of them work? Thank you!
 
https://github.com/MonitorControl/MonitorControl/releases
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by waydabber** [comment]
Can you try beta7? Does it work better? Thank you!

**Comment by waydabber** [comment]
Hi, it is considered normal that there is a lower limit for contrast control. The volume issue is strange - but it is only controlled if the display is set as volume out (using software like Boom or other app that adds a software layer over the direct DP digital audio will make this function not working) and some displays simply don't like their audio controlled via DDC.

Also you could try [m1ddc](https://github.com/waydabber/m1ddc) to see if that can control the audio (if so, then the problem lies with MonitorControl).

I'll close this issue as this might be a display specific issue, but please feel free to reply and ask for a reopen if you think there is anything else for me to help with! Thank you!
