### ISSUE TITLE
Hide menu icon when no external monitor is connected

### ISSUE THREAD

**Issue by mufumade** [MonitorControl/MonitorControl#536]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

Simple checkbox in the settings so the user can chose wether he likes to hide the menu icon when no external monitors are connected.

### Describe alternatives you've considered

No alternatives.

**Comment by waydabber** [comment]
I am not sure about this one. There is already an option to hide the icon - selectively hiding/unhiding it based on which displays are present might create a confusion, but I understand why somebody would some prefer this one. An other thing is that now there are so many diverging minor requests on all fronts that solving all these will require an excessive amount of advanced preference items (I can like already count dozens) which makes me a bit cautious - maybe we should focus on the essentials only instead of creating an app that is customizable beyond a reasonable point? But from a technical point of view this request is absolutely doable.

I'll leave it open and let's see what others are saying - @JoniVR?

**Comment by JoniVR** [comment]
I agree with @waydabber, this is a bit too much of a "special use case" that 99% of our users probably won't care about. It adds a bit extra maintenance burden and complicates the app a bit too much to be worth it imo.

@mufumade You're of course always free to fork the project (yay open source) and build it into your own fork, or (and I haven't tested it so idk if it's possible), you can try creating an automator action that launches/kills MonitorControl based on the amount of displays connected.

**Comment by mufumade** [comment]
So my main point is that if you use your laptop on the go without any external monitors the menu space can be pretty limited. Especially on the smaller models. So to hide the menu item that has no use if no monitor is connected seems a good enough reason to me.

But thank you guys for your quick consideration :)

**Comment by waydabber** [comment]
Hi @mufumade - I understand the reasoning. What I'd recommend is if you move the less important icon to the leftmost of the menu bar, macOS tends to hide them on a small screen if the currently open app has many menu items so there is not enough rooms left.

**Comment by waydabber** [comment]
Hey all, I'll now close this feature request as both @JoniVR and I are concerned about making MonitorControl a bit unfocused with all kinds of feature requests now. If this comes up in the future or will see a demand for this feature we'll revisit it! Thank you!

**Comment by waydabber** [comment]
Apparently this issue is requested by others as well.

https://github.com/MonitorControl/MonitorControl/discussions/590

Now that Advanced settings hides extra options throughout the preference panes even more arcane options could be added without confusing novice users so we can probably add this as well.

**Comment by waydabber** [comment]
I added this one. See the updated screenshot here:

https://github.com/MonitorControl/MonitorControl/discussions/596
