### ISSUE TITLE
Dell 2721H No Audio Control

### ISSUE THREAD

**Issue by thezdman** [MonitorControl/MonitorControl#553]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Volume not working (no slider available) for Dell 2721H monitor.

### Expected behavior

expect to see volume control when clicking icon

### Anything else?

![Screen Shot 2021-09-01 at 2 12 16 PM](https://user-images.githubusercontent.com/89939524/131730510-be2b470e-da7e-4423-9fbc-d8d3493b1f36.png)

### Environment Information (please complete the following information)

```markdown
- macOS version:11.5.2
- Mac model:M1 Mini
- MonitorControl version:3.0.0 build 2869 Apple Silicon
- Monitor(s):Dell S2721H
- Monitor Cable(s)/Connection(s):HDMI
- Apple Silicon/M1 (yes or no):YEs
```

**Comment by waydabber** [comment]
Hi @thezdman, the 2018 Intel mini and the 2020 M1 mini does not support DDC control over the HDMI port (the required i2c communication channel is being blocked, this is probably a design issue on Apple's part). You need to use one of the USB-C ports (using an USB-C to HDMI dongle is fine, most - but not all - support passing through DDC commands). This is why you see `Software Only` as Control method instead of `Hardware (DDC)`.

Since there is no much to do about this, I'll close this issue for now, but feel free to comment anyway if I can be of any help with this or you have further questions! :)
