### ISSUE TITLE
Software dimming function resets to full brightness a few seconds after adjusting.

### ISSUE THREAD

**Issue by giulianofichera** [MonitorControl/MonitorControl#559]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

When enabling **software** dimming for an HDMI TV (connected through a USB C hub) the TV dims accordingly but suddenly returns to full brightness.
This bug occurs sooner when my mouse changes display, I click something or I move the mouse rapidly.
Even without performing any action, the TV returns to full brightness inevitably.
I have tried all possible settings combinations: changing the brightness using the keyboard, the software slider, changing the brightness for all screens and also independently.
Also tried a reboot, reinstall, reinstall + reboot, unplugging and plugging the usb hub.

### Steps to reproduce

1. Enable software dimming if required option.
2. Change brightness (using the keyboard shortcuts or the menu bar slider).
3. Move the mouse between screens to speed up the bug reproduction, or simply wait for it to happen some seconds after without any intervention.

### Expected behavior

The software brightness adjusts itself accordingly and remains in the desired brightness level until changed.

### Anything else?

https://user-images.githubusercontent.com/80286668/132044342-9ae1b5ff-ba66-4d05-b194-b4f1aa9a0bf2.mp4

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.5.2 Big Sur
- Mac model: MacBook Air (M1, 2020)
- MonitorControl version: 3.0.0 Build 3095
- Monitor(s): Philco Pld50us9a1 4k
- Apple Silicon/M1 (yes or no): yes

- USB C Hub used: Anker (https://www.amazon.com/Anker-PowerExpand-Adapter-Delivery-Ethernet/dp/B087QZVQJX/ref=sr_1_5?dchild=1&keywords=anker+usb+c+hub&qid=1630689207&sr=8-5)
```

**Comment by waydabber** [comment]
Hey, can you show me a printsceen of the `Displays` tab in `Preferences`? Thank you!

**Comment by waydabber** [comment]
Never mind, I just wanted to make sure that Hardware Control is disabled under Displays for the TV bat as I see it should be disabled since you have Volume enabled and it is not showing which means the display is forced to use Software Control.

The issue is indeed a weird one. Somehow the gamma table is being reset for some reason immediately. The fact that it happens upon some activity is because on most macs gamma table changes are not reflected on the screen unless there is an event that causes some part of the screen to redraw. Don't you use any other software that does gamma table manipulation? Maybe some screen management app or anything else that changes the displays, gamma, tint, etc of the display?

**Comment by waydabber** [comment]
Hi, I looked at the Anker device in more detail. It seems like the HUB is using some kind of compressed video streaming technology (marketed as 'Anker Media Display') to achieve 4K@60Hz via the HDMI port alongside USB3 speeds and gigabit ethernet. Or maybe uses chrome subsampled HDMI (?). Otherwise the standard 10GB bandwidth of USB-C would only allow USB2 speeds alongside full uncompressed 4K video at 60Hz. An other option is that maybe it uses the new DisplayPort 1.4 HBR3 internally and then converts the signal to HDMI, which theoretically could allow for the use of only two displayport lanes and still have room form USB 3+ speeds for the other ports. Since some kind of wizardry going on here, it might be possible that this interferes with the way how macOS handles gamma tables.

You might want to try changing the color calibration using the [expert mode of the built in calibration tool](https://osxdaily.com/2015/10/14/access-expert-mode-screen-color-calibrator-mac-os-x/) and see how that works and if the issue persists with a custom calibration applied.

I also recommend trying a simple native USB-C to HDMI adapter to see if you have the same problem with that.

I'll convert this issue to a discussion as it might result to conclusions beneficial to others as well. Hopefully more info will come to light.
