### ISSUE TITLE
allow to hide LG software volume control

### ISSUE THREAD

**Issue by foss-** [MonitorControl/MonitorControl#564]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

While it is possible to hide the monitor software showing and only use macOS UI to show screen brightness adjustments, I think it is not possible to do the same for volume changes.

### Describe the solution you'd like

It would be nice if it was also possible to hide monitor software showing and only use macOS UI to show volume adjustments.

### Describe alternatives you've considered

This is what is corrently shown for an LG Ultra HD monitor connected via USB-C. The monitor software is shown overlaying the macOS UI.
![LG Ultra HD monitor](https://user-images.githubusercontent.com/5708172/132210593-db41bc02-f949-4341-934d-f0e3b5a953f5.JPG)

### Anything else?

In Settings > Displays there is the option to `Disable macOS volume OSD`. This request is about an option to `Disable monitor volume OSD`.

**Comment by waydabber** [comment]
Hey @foss-. Some LG displays allow suppression of the volume OSD by issuing a disable OSD command shortly after changing the volume. But for most of the time this makes the volume operations slow, causes the monitor OSD to flicker (as it is still displayed briefly) and for some displays the very same command permanently disables OSD which is obviously not good :) Version 2.1.0 had this feature but it was removed from 3.0.0 due to the complaints. We added the option to hide the macOS volume OSD instead so at least there would not be two overlapping OSDs.
