### ISSUE TITLE
Speaker connected to the display via jack but no control with the program !

### ISSUE THREAD

**Issue by is4lloum** [MonitorControl/MonitorControl#578]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Discussion

Thank for your great job.
Sry for my bad English but I try to explain the situation, i have a Samsung display (U28E590) without integrated loudspeakers, so i connected a loudspeaker to the display via jack, the bars for the sound are displayed and moved up/down when i use volume keys on the keyboard but have no effect on the sound (No changed)
I don't know if this is an issue or something like this is not supported.
Thank you in advance for your answer.

**Comment by waydabber** [comment]
Hi @is4lloum - this seems to be a display specific issue. Some displays with external speakers connected might need a special speakerSelect (0x63) command to work and also check for audioJackConnectionStatus (0x65). This is rare however, most of the time this is not the case (I have an LG with a jack and no built in audio and it works for example) as displays tend to autodetect the audio output (since yours don't even have an internal speaker, it makes no sense anyway to use these commands, but still the display firmware might be buggy in this regard). You might want to try to use ddcctl and send direct commands to the display to figure out what needs to be done for proper control. If you come to a conclusion, we might add a feature request to add a special option for this in the advanced section of Displays.

I'll convert this issue to a Discussion. Please let me know if you come up with something. Thank you!
