### ISSUE TITLE
MonitorControl not working properly on M1 Macbook Air

### ISSUE THREAD

**Issue by brypwn** [MonitorControl/MonitorControl#580]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Only works via software dimming even though the app detects that DDC is available. However, after dimming the screen through the slider in the menu bar, it automatically goes back to the normal brightness after a few seconds, and the settings do not stick. Am using a Prism+ C270, via USB-C to HDMI cable.

### Expected behavior

Brightness settings should stick after setting. 

### Anything else?

No

### Environment Information (please complete the following information)

```markdown
- macOS version: Big Sur 11.5.1
- Mac model: M1 Macbook air
- MonitorControl version: 3.0.0
- Monitor(s): Prism+ C270
- Monitor Cable(s)/Connection(s): USB-C to HDMI
- Apple Silicon/M1 (yes or no): Yes
```

**Comment by waydabber** [comment]
Hey @brypwn - DDC detection is not 100%. Currently it only means that the port lets DDC commands through, but since displays don't uniformly respond, we disabled the logic which requires strict protocol conformity during communication checks and presume monitor compliance even if the monitor might not actually be controllable via DDC.

Please see [this discussion](https://github.com/MonitorControl/MonitorControl/discussions/561) about returning brightness in software mode. If you have any further question regarding this or you feel that your case is different, just pop a comment under the discussion. Thank you!
