### ISSUE TITLE
Stopped working on M1 Mac Mini after updating MacOS to v11.6

### ISSUE THREAD

**Issue by parasshah195** [MonitorControl/MonitorControl#604]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Looked through [the wiki](https://github.com/MonitorControl/MonitorControl/wiki)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the bug

I'm using an LG Ultrafine 27" 4K monitor and after updating to MacOS v11.6 yesterday, the volume and brightness keys stopped functioning. Even the volume slider in the menu is in disabled state for monitor speakers.

Here's how it shows:

![monitorControl volume test M1 MacOs 11 6](https://user-images.githubusercontent.com/18551588/133883582-d77e5a2b-c3c2-469b-867f-eaf0976901cf.jpg)

### Steps to reproduce

Update to MacOS 11.6 on an M1 machine with an external monitor

### Expected behavior

For the volume and brightness control to work as normal like with MacOS v11.5 and before

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6 Big Sur
- Mac model: Mac mini (M1, 2020)
- MonitorControl version: 3.0.0 build 2869 - Apple Silicon
- Monitor(s): LG Ultrafine 27" 4K
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Can you give me a screenshot of the Displays section in Preferences? Thank you.

**Comment by parasshah195** [comment]
@waydabber 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/18551588/133893046-eedc9b31-968f-42e4-b598-04d43ae812b8.png">

**Comment by waydabber** [comment]
Interesting. It should work I think. Did you try a preferences reset under General/Advanced?

**Comment by waydabber** [comment]
But the fact that it shows an OSD lock means that the app is in a state of reconfiguration. Whenever there is a display configuration change or sleep event, the app is waiting for a while until things settle. During this time, an OSD Lock is displayed. This should go on for 2-5 seconds depending on the underlying cause. If this goes on indefinetly then it means that the system is constantly reconfiguring its displays and sends a `CGDisplayRegisterReconfigurationCallback` signal to the app.

This might happen due to some hardware problem or a misbehaving app which interferes with the inner workings of the system. I don't think 11.6 itself causes this issue on its own but I have no way of trying it.

**Comment by waydabber** [comment]
(If you are up to it, you can download the source code and run it in XCode. Then in the deugger you'll see what is happening as the console shows warnings for ongoing reconfigurations.)

**Comment by waydabber** [comment]
Hi parasshah195,

I'll close this issue now. If I can help you in any way with this or you can add any new information, please let me know! If other reports will emerge about problems with 11.6, we can also reopen this one obviously. Until then I'd look for misbehaving apps or hardware issues that might be causing repeated display reconfiguration (I see from the toolbar that you use a bunch of apps, some of which might be interfering with MonitorControl?) - please let me know if you find some incompatibility as it might be useful for other users as well!

Thank you!

**Comment by parasshah195** [comment]
Funny that it automatically started working again. Maybe all it needed was a restart?

The volume slider on the menu bar is disabled, but the keyboard keys (both volume and brightness) are working fine. So, no complaints.

<img width="1913" alt="image" src="https://user-images.githubusercontent.com/18551588/134001097-13f539a8-bbad-4998-b1ea-52581864953a.png">

Thank you very much for your prompt response @waydabber

**Comment by waydabber** [comment]
Hey @parasshah195 - sorry to say but MonitorControl can't override the native audio panel slider and digital outputs are not volume controllable in macOS, that's why you see it as disabled. This is a limitation put in place by Apple as they don't allow tampering with those controls. This is why MonitorControl has its own volume slider (you must enable the app menu icon for it).
