### ISSUE TITLE
No volume control on Dell UltraSharp 34 Curved U3419W monitor

### ISSUE THREAD

**Issue by gianpaj** [MonitorControl/MonitorControl#622]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] I have read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

I can't get the volume to work on a Dell UltraSharp 34 Curved U3419W monitor.

### Expected behavior

control audio volume (software or hardware)

### Anything else?

Using `ddcctl` it didn't work either

```
$ ddcctl -d 1 -v 0
D: CGDisplay 7CA9C7D3-028C-CC9F-7109-C67C359BD9F2 dispID(#724048344) (3440x1440 0°) 109.00 DPI
I: found 1 external display
I: polling EDID for #1 (ID 724048344 => IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@3)
I: got edid.serial: HPKZ5T2
I: got edid.name: DELL U3419W
D: action: v: 0
D: setting VCP control #98 => 0
```

Related to #479 ?

![image](https://user-images.githubusercontent.com/899175/134800530-5cd2ebd3-925d-4ed4-9a9c-47ace4f01fe4.png)

Without running MonitorControl I get this image indicating that the volume cannot be controlled...
![image](https://user-images.githubusercontent.com/899175/134800675-de64f359-ab8b-4aff-8ab9-115025dd9b40.png)

I have also a MacBook pro 2019 and connecting with a USB-C cable to a Dell docking station, I can control the audio (without needing MonitorControl)

### Environment Information (please complete the following information)

```markdown
- macOS version: 10.15.7 Catalina
- Mac model: MacBook Pro (Retina, 15-inch, Mid 2014)
- MonitorControl version: 3.1.0
- Monitor(s): Dell UltraSharp 34 Curved U3419W
- Monitor Cable(s)/Connection(s): 
Macbook -> HDMI - Dell HDMI connection
- Apple Silicon/M1 (yes or no): no
```

**Comment by JoniVR** [comment]
Hi, some questions:
* Is brightness working? 
* Can you try v2.1.0 and report if it's working there? (I doubt it, but worth a shot, see #479)

My best guess is that the Dell Docking station does not properly forward the commands, but I'm not sure. I know Dell tends to do some weird stuff with some of their docks due to them using USB-C instead of thunderbolt.

**Comment by gianpaj** [comment]
Hi @JoniVR , thanks for that.

I've

**Comment by waydabber** [comment]
Hi @gianpaj

it seems like DDC does not work in general, so volume control via DDC will not work for sure either. You might want to check if DDC/CI is not disabled on your display (Dell displays usually have an option for it) or you might want to try using DisplayPort as it might work better. Also you can try if [Lunar](https://lunar.fyi) works with your setup. If none of the these apps work, then probably there is some incompatibility - @alin23, the maker of Lunar put together a great FAQ item about the most common issues which I highly recommend (with his permission):

https://lunar.fyi/faq#brightness-not-changing

Since it seems there is noting much we can do on MonitorControl's side, I'll close this issue but please let me know if feel we can be of help in any way! Thank you!
