### ISSUE TITLE
Save/restore brightness value in software mode

### ISSUE THREAD

**Issue by xand3r40r93** [MonitorControl/MonitorControl#718]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I using my monitor on full brightness and controlling brightness in software mode. For my monitor, it's like 'flicker free' mode. After system restart brightness value always is 100%.

### Describe the solution you'd like

Just save/restore brightness value in software mode at startup or closing program.

### Describe alternatives you've considered

...

**Comment by waydabber** [comment]
The app actually saves software brightness but to avoid behavior that might be puzzling to some users, the saved software dimming values are restored only upon wake or display configuration change and not during application startup (it is intentional, most people probably don't restart their macs or the app very often anyway but use sleep instead). The `Upon startup or wake`/`Apply last saved values` are relevant only for the DDC component of the brightness, not the software component (when waking from sleep, software dimming is reapplied regardless of this setting but on startup it is never reapplied). It might be reasonable to change how this works (we should clarify that the `Upon startup or wake` option is only for DDC only and there could be a setting about reapplying software dimming upon app startup).

**Comment by waydabber** [comment]
I did some tweaks here and there + changed the behavior. Now if `Upon startup or wake`/`Apply last saved values` is selected, then software and combined brightness will be restored upon app start. Since this is not a default startup option and also there is a separate option for allowing zero brightness with a proper warning, this seems to be acceptable.

**Comment by waydabber** [comment]
<img width="842" alt="Screen Shot 2021-10-17 at 11 23 46" src="https://user-images.githubusercontent.com/37590873/137620936-f40a0420-0eec-43de-9d53-afdfac166c85.png">
