### ISSUE TITLE
Add DDC display input control to the menu

### ISSUE THREAD

**Issue by waydabber** [MonitorControl/MonitorControl#720]
### Feature Request

Add display input selector options to the menu (the presence of the options and the offered inputs should be user configurable).

**Comment by pjanx** [comment]
Seconding this request, and offering [sample code for Linux](https://git.janouch.name/p/desktop-tools/src/branch/master/input-switch.c). I'm currently trying to figure out where to get input codes for Thunderbolt, though.

**Comment by waydabber** [comment]
Hope I'll have more time and I'll implement it. All the basic parts are in MC already but needs a nice GUI.

**Comment by pjanx** [comment]
I've written to VESA, FWIW.

**Comment by waydabber** [comment]
Display input codes and names are rather random, my LG display's inputs do not correspond to the usually accepted list for example. For this to work there must be a setting where the user can customize the values and corresponding names (the default list can be a starting point though).

**Comment by pjanx** [comment]
As a data point, my BenQ PD3220U uses standard DisplayPort and HDMI{1,2} values, IIRC Dell U2412M also did.

`ddcutil capabilities` extracts a list, so by default you could assign names according to MCCS 2.2a + 0x15 for Thunderbolt, and let the user customize it. It's just strings, anyway, could be "NUC" and "MBP".

**Comment by pjanx** [comment]
Alright, I have found out that I have no use for MCCS Input Source. Because when I switch the input this way, my BenQ will not reconnect peripheries, and so there already needs to be output, or the display switches back before it switches USB, and I can't wake that computer's video output up.

Rather, I need to use the "KVM switch" feature, hidden underneath:
```
   Feature: E4 (Manufacturer specific feature)
      Values: 01 02 (interpretation unavailable)
```
and, for completeness, that works for the following panel, marketed to be "designed with the MacBook in mind":
```
      Mfg id:               BNQ
      Model:                BenQ PD3220U
      Product code:         32813
      Serial number:        W5K00458019
      Binary serial number: 21573 (0x00005445)
      Manufacture year:     2019,  Week: 22
```

@waydabber What do you think, is a simple per-display/manufacturer toggle possible? As in, a set of numbered buttons that would set that VCP, pre-toggled by the VCP's current value. And ideally with keyboard shortcuts, but that's a lot to ask for. Should I start a new issue?

I suppose I should be able to invoke it with https://github.com/waydabber/m1ddc until then.

**Comment by waydabber** [comment]
so instead of display input for your display e4 must be used with values 01 and 02? This seems to be a rather display specific things, but since this control will have an option to override the VCP and also I'd like to make the input list customizable, you could customize the input switch function (once implemented) to use this manufacturer specific VCP with the values is needs.

**Comment by pjanx** [comment]
It's more like a separate function, in addition to display switching (it can only switch between two USB targets, unlike Input Source). It calls for some possibility to invoke custom functions, and perhaps an internal database of these, such as:

```
<display>
  <match mfg="BNQ"/>
  <control name="KVM Switch" vcp="E4" type="toggle"/>
  <input-source include="mccs2.2a"/>
  <input-source value="15" name="Thunderbolt 3"/>
</display>
```

I think ddcutil has something similar.

It sounds like a major task, I'll resolve it for myself using simpler means. I have zero Swift/Xcode experience.

**Comment by stiligFox** [comment]
Just want to throw in my +1 - was going to request this feature and see it's already open. I stream, so I tend to switch from macOS (on DisplayPort) on one monitor to my Nintendo Switch (on HDMI) so that I watch the game directly while streaming, and having to do the whole reach around to change inputs with the OSD is cumbersome! Would love the option to be able to switch inputs from within macOS. Thanks!

**Comment by klsetzer** [comment]
+1 This is my primary interest in a tool like MonitorControl. I'm currently using ddcctl + Alfred (which is alright).

**Comment by qoodanny** [comment]
I am looking forward to see input control for LG Monitor!

**Comment by vinschi** [comment]
+1 would be nice that monitor control could switch the inputs as displaybuddy

**Comment by Ilapides** [comment]
+1 Why I'm here.

**Comment by vju42** [comment]
+1 yes this is required by me as well. I have a dual-4K setup and use both a business MacBook Pro 2021 as well as a private macmini m1 2020. This would allow with a shortcut to move one or both screens to the other computer and with the new macOS transparency use only one mouse and keyboard.

**Comment by orpiske** [comment]
+1 I'd love to have this feature as well!

**Comment by waydabber** [comment]
Hi @orpiske - just implemented this in BetterDisplay (free feature), will be available in the next version (will be released in the coming days if things go well).

![](https://user-images.githubusercontent.com/37590873/201016553-9c8140c4-24db-499b-bae5-5059b0c26865.png)

https://github.com/waydabber/BetterDisplay/issues/604

This will probably not make it into MonitorControl anytime soon except if someone from the community adds it as a nicely done PR, the door is always open! :)

**Comment by orpiske** [comment]
@waydabber you rock! I'll take a look at it :D

**Comment by waydabber** [comment]
Note: the beta is available at https://github.com/waydabber/BetterDisplay/releases/tag/v1.3.5-beta. If you have any issues with it you can let me know at the [BetterDisplay project's GitHub issues tab](https://github.com/waydabber/BetterDisplay/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc). I generally don't want to confuse the two apps, just mentioned this here since I know a lot of folks wanted it.

**Comment by findthebug** [comment]
yes, would be cool feature

**Comment by waydabber** [comment]
This feature probably won't be implemented in MC, check out [BetterDisplay](https://betterdisplay.pro) for this feature as it's been available there for a while now for free.

**Comment by waydabber** [comment]
As the feature set of MonitorControl is now considered final by the team, I'll close this issue. Of course if somebody comes along with a well implemented PR containing this feature, it will be approved.

**Comment by Dentrax** [comment]
Hey! I just fresh installed this app by thinking I could change the input source but then I hit this issue, which is abondoned. It seems people did stop writing on this issue after it has implemented in BetterDisplay.

BetterDisplay would a bit overkill for my need: I'd like to change input source by pressing a key on keyboard or moving cursor to the edge.

I was wondering if its because of a technical blocker or by-design.

**Comment by appdcs** [comment]
Input control is not available in BetterDisplay, via hotkeys, after the trial run ends.
I would recommend reopening this issue and making simple input switching available in MonitorControl.

As @Dentrax said, BetterDisplay is **overkill** compared to MonitorControl. The only think missing from MonitorControl IMHO is switching to an input via hotkey.
