### ISSUE TITLE
Managed Preferences

### ISSUE THREAD

**Issue by iceman60** [MonitorControl/MonitorControl#747]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

I'm packaging MonitorControl at work and I need to control updates manually. I actually can't control any preferences using my MDM platform.

### Describe the solution you'd like

Use the /Library/Preferences to control MC configurations. First I need to control _Automatically Check for Update_ setting and be able to disable the  _Check for updates.._ menu.

### Describe alternatives you've considered

Blocking update retrieve by FW rules

### Anything else?

thanks for your work !

**Comment by iceman60** [comment]
Nope. 

Envoyé de mon iPhone

**Comment by waydabber** [comment]
Oh, that just changes the setting itself, does not gray out or hide the setting. There is currently no logic for that, a new `DisableAutoUpdate` setting should be implemented while making sure that a preferences reset does not wipe this setting.

An alternative solution until that time is to block the URL to the appcast.xml on the firewall so the app can't reach the update feed and check for updates.

The appcast feed is: feed:https://monitorcontrol.app/appcast.xml

**Comment by bradtchapman** [comment]
Managed Preferences would be nice—perhaps you should consider donating a lot more since you are clearly discussing an enterprise deployment—but we must consider more essential MDM-less deployments that ship with a "default" configuration, that still allow the user to make changes.  Perhaps they want to get automatic updates?

Apple's Workgroup Manager on Open Directory was great because you could set a preference "once" and then allow the user to change it.  Managed Preferences with MDM does not allow that sort of flexibility by design.

Deploying a pre-configured .plist doesn't work correctly. For instance, I tried editing the binary plist with PlistEdit Pro to set "SUEnableAutomaticChecks" to "false."  The app still launched with "Automatic Updates" enabled.  Prior to editing the file, I made sure MonitorControl was quit, ran "killall cfprefsd" to flush the cache, and then edited the file.  On the next launch, MonitorControl ignored my setting and auto updates were enabled anyway.

**Comment by waydabber** [comment]
Well, changing settings is rather important for MonitorControl as all relevant stuff is constantly stored in user preferences not only simple settings. For a proper lockdown of some preferences in an enterprise environment to work a lot more work should be done. Obviously a generous enterprise donation would greatly accelerate the work on this but this is not generally on the radar at the moment.

Changing the SUEnableAutomaticChecks in the plist file should work (but note that there is an other setting that can be toggled which manages automatic download of the updates which is not exposed in the preferences GUI but can be enabled in the sparkle update popup window) if the cache is properly flushed (it is best to restart the mac or at least log in/out and also make sure that the preference file version under the ByHost folder is deleted as well as that can act as a secondary permanent storage for preferences).
