### ISSUE TITLE
 Increase max brightness for 2021 Macbook Pros

### ISSUE THREAD

**Issue by sagz** [MonitorControl/MonitorControl#759]
### Before opening the issue, have you...?

- [X] Searched for existing issues

### Is your feature request related to a problem? Please describe

Principally, this would be useful for working outdoors in sunlight.

Push the brightness of the new XDR display macbook pros past the default allowance of 500 nits. 
I want to be able to push the display to the advertised "sustained 1000 nits" every once in a while for short durations when doing a video call outdoors.

### Describe the solution you'd like

Apple advertises the new Mini-LED MacBook Pro 14 with a peak brightness of up to 1600 nits and a sustained brightness of 1000 nits, but these values seem to be limited to HDR contents. Standard SDR contents are [limited to 500 nits](https://www.notebookcheck.net/The-new-MacBook-Pro-14-only-manages-500-nits-with-SDR-contents.575327.0.html), which is comparable to the current MacBook Pro 13.

### Describe alternatives you've considered

I'm wondering if it's possible to hack around this somehow.

Is it possible to simulate HDR content as an overlay across the screen? It's a dirtier hack for sure, but might work (there are reports that with HDR windows, MacOS makes only those windows in HDR while other SDR windows stay in lower brightness)

Another hack I wonder is if one could create a 'custom preset' from such a list:
![image](https://user-images.githubusercontent.com/964843/139787202-0c95fb4f-fd9c-4139-a939-e53d37be2aa7.png)

**Comment by waydabber** [comment]
I think it might be possible but I have no MBP and even don't have a HDR display to experiment with (only a humble 13" MBA with 8Gigs of RAM and a trusted old SDR display lol). :)

**Comment by MacInTheNet** [comment]
If you can solve the problem I think all the community that is discussing this around the world (on macrumors for instance) would happily buy you whatever you need XD

**Comment by namorrellek** [comment]
as a photographer i would be very happy to use a brighter macbook display outdoors. where/how can i support the development of this feature?

**Comment by waydabber** [comment]
well I don't think I can work on that without an actual MacBook Pro and even if I had one there is no guarantee so the contribution is not guaranteed to yield any return. It would be unreasonable to ask ppl to contribute that much for this feature and based on the average rate of donations, it will take about 3-4 more years for the project to gather enough money so I could buy one from my share. I have some ideas but this would involve heavy experimentation to see what works and what doesn't.

But surely there are other coders who have some experience in this department with a new MBP. I'll add a "Help Wanted" badge to this issue, hopefully that will attract someone to start working on this from the community. If by some miracle I can lay my hands on a new MBP sometime in the future and the problem is not solved yet, of course I'll try whatever (silly or not so silly - who knows) ideas I have regarding making this happen.

**Comment by waydabber** [comment]
(but hey if you are a photographer and use HDR images, the nMBP display should already show them with higher brightness in supported apps).

**Comment by namork** [comment]
dear waydrabber. i work in lightroom and the user interface would be the most important thing to make readable better in the sunlight.

**Comment by waydabber** [comment]
I have a way of achieving this now at least in principle. I plan to add this to [BetterDummy](https://github.com/waydabber/BetterDummy) as it has the core technologies (screen virtualization) that is needed (short version: a virtualized screen will be streamed to a persistent full screen view with custom metal tone mapping layer to extend the dynamic range into HDR/EDR headroom beyond SDR - the result should be an SDR screen that can crank up the max brightness to full HDR peak brightness - and probably kill the display on the long run if not used wisely lol).

**Comment by waydabber** [comment]
I'll convert this into a discussion since this probably won't make into MonitorControl.
