### ISSUE TITLE
Sound control not working on Samsung S32AM700PC

### ISSUE THREAD

**Issue by allenmien** [MonitorControl/MonitorControl#801]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

hi, 

My monitor is SAMSUNG S32AM700PC.
The Sound Control does not work well, please help me, thanks

### Expected behavior

Sound Control work well

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6 Big Sur
- Mac model: MacBook air M1 (13-inch, 2020)
- MonitorControl version: 4.0.2
- Monitor(s): SAMSUNG S32AM700PC
- Monitor Cable(s)/Connection(s): usb-c
- Apple Silicon/M1 (yes or no): yes
```

**Comment by waydabber** [comment]
Can you please try [m1ddc](https://github.com/waydabber/m1ddc) or alternate apps like [Lunar](https://lunar.fyi) and see if volume control works with those apps? If not, then it is most probably a display issue.

**Comment by waydabber** [comment]
Hey @allenmien, I'll close this issue for now but please feel free to respond (I'll get notified). If this turns out to be a MonitorControl issue, not a display specific one then we'll investigate further and reopen the issue. We'll need more descripotion of what "does not work well" mean exactly. :) Thank you!
