### ISSUE TITLE
INNOCN 27C1U Adjusting the sound of the monitor does not work 

### ISSUE THREAD

**Issue by caifenglin** [MonitorControl/MonitorControl#818]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

On my joint innovation display, the sound does not work, and the brightness can be successfully adjusted to display joint innovation 27c1u，ddcctl is used to adjust the sound without error, but it has no effect

### Expected behavior

I hope it can support adjusting the sound of the monitor，Display parameter link https://item.jd.com/100013814761.html，I hope the sound adjustment function can be repaired. Thank you very much

### Environment Information (please complete the following information)

```markdown
- macOS version:10.15.7
- Mac model:
- MonitorControl version:4.0.2
- Monitor(s):27C1U
- Monitor Cable(s)/Connection(s): Display Port
- Apple Silicon/M1 (yes or no):no
```

**Comment by waydabber** [comment]
Hi @caifenglin - I am afraid this is a display specific issue. I advise you to try changing the volume via alternate apps that use DDC for control, like [ddcctl](https://github.com/kfix/ddcctl) or [Lunar](https://lunar.fyi). If neither of the works then the display is probably incompatible with the DDC command that adjusts the volume and there is nothing we can do about it I am afraid. :(

I'll convert this into a discussion so that others with similar displays might join and share their experience.
