### ISSUE TITLE
LG Ultrawide Volume Control 

### ISSUE THREAD

**Issue by Duskcyclist** [MonitorControl/MonitorControl#824]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Hi there,

I'm having a few issues with the volume control on my LG 34WN80C-B UltraWide Monitor. Using the Mac keyboards to turn the sound up & down does work but it brings up the LG volume indicator overlay on the screen which is a bit in the way & not as sleek as the Mac volume indicator. While the Mac volume indicator still shows up, it is hidden b
![IMG_3028](https://user-images.githubusercontent.com/20780273/144662294-dafe7c3b-a617-4a8c-8de0-535deee851d3.JPG)
ehind the LG volume indicator. Photo attached.

The other issue is that when I mute the system audio (via the Mac keyboard button) it does mute however, when I unmute, the LG monitor stays muted. The only want to unmute is to toggle the nob below the monitor. 

Otherwise, this app is awesome & does a great job. 

### Expected behavior

I'd love for the volume indicator on the Mac to only show up & the LG volume indicator remain inactive. I've tried SoundSource & it works in that regard. Also MonitorControl does work perfectly when adjusting the brightness (no LG monitor overlays).

I'm also hoping muting & unmuting would work as expected without having to toggle LG monitor settings.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.6.1
- Mac model: 15-inch, 2019
- MonitorControl version: 4.0.2
- Monitor(s): LG 34WN80C-B UltraWide Monitor
- Monitor Cable(s)/Connection(s): USB-C
- Apple Silicon/M1 (yes or no): no
```

**Comment by JoniVR** [comment]
Hi @Duskcyclist!

> Using the Mac keyboards to turn the sound up & down does work but it brings up the LG volume indicator overlay on the screen which is a bit in the way & not as sleek as the Mac volume indicator. While the Mac volume indicator still shows up, it is hidden behind the LG volume indicator. 

This is expected behaviour. The difference between things like SoundSource is that MonitorControl controls the display itself instead of using a virtual audio channel. We used to have a feature that spammed a certain command that removed the LG OSD (aka overlay), but it didn't work very reliably, so it got removed. There's not much more we can do there.

> Also MonitorControl does work perfectly when adjusting the brightness (no LG monitor overlays).

This is LG specific. I have almost the same model as you do. There is no LG OSD for brightness like there is for volume. The reason there's an OSD for volume is because you can use the knob to adjust volume, it's displaying that OSD.

> The other issue is that when I mute the system audio (via the Mac keyboard button) it does mute however, when I unmute, the LG monitor stays muted. The only want to unmute is to toggle the nob below the monitor.

Can you try:

1. Preferences > Displays > Toggle `Show advanced settings` at the bottom
2. Toggle `Enable Mute DDC command` for the display.

**Comment by Duskcyclist** [comment]
Thank you so much for your speedy response! I really appreciate it. I can certainly live with the LG overlay. All good. But that mute toggle suggestion did fix it! Much better. Sorry I didn't see that option to show advanced settings.

Really appreciate your assistance & great app! Have a wonderful weekend.
