### ISSUE TITLE
Mute does not actually mute the speakers.

### ISSUE THREAD

**Issue by Frizzacazzi** [MonitorControl/MonitorControl#842]
### Before opening the issue, have you...?

- [X] Searched for existing issues
- [X] Read through [the Monitor-Troubleshooting Wiki](https://github.com/MonitorControl/MonitorControl/wiki/Monitor-Troubleshooting)
- [X] Updated MonitorControl to the latest version (if applicable)

### Describe the issue

Turning the volume all the way down, or using the mute key does not mute the speakers, it only lowers the volume.

In other words, the value interpreted as 0, no volume by the Mac does not correspond to the actual mute on the monitor speakers?

I tried to look for existing issues and in the wiki and I didn't happen to find anything related to my issue..

Thanks!

### Expected behavior

Turning the volume all the way down Is supposed to mute the speakers.

### Environment Information (please complete the following information)

```markdown
- macOS version: 11.2
- Mac model: 2,6 GHz Intel Core i7 quad-core
- MonitorControl version: 4.0.2
- Monitor(s): Samsung C34J791
- Monitor Cable(s)/Connection(s): Thunderbolt
- Apple Silicon/M1 (yes or no): No
```

**Comment by JoniVR** [comment]
Hi, this is mostly our fault, because it should be part of the wiki.

Can you try:

1. Preferences > Displays > Toggle `Show advanced settings` at the bottom
2. Toggle `Enable Mute DDC command` for the display.

I'll try to get around to updating the wiki + moving it outside of Github wiki and into the monitorcontrol.app website, so external contributors can contribute to it.

**Comment by Frizzacazzi** [comment]
That worked like a charm, thanks for your kindness and your fantastic work ♡
